[package]
name     = "python"
version  = "3.14.6"
release  = 3
summary  = "CPython — the Python programming language interpreter"
homepage = "https://www.python.org/"
license  = ["Python-2.0.1"]
arch     = ["x86_64"]

depends     = ["glibc", "zlib", "openssl", "bzip2", "libffi", "xz", "ncurses", "readline", "gdbm", "mpdecimal", "sqlite", "expat", "util-linux"]
provides    = ["python3"]

[[source]]
url    = "https://www.python.org/ftp/python/3.14.6/Python-3.14.6.tar.xz"
sha256 = "143b1dddefaec3bd2e21e3b839b34a2b7fb9842272883c576420d605e9f30c63"

[steps]
build = '''
cd "Python-$version";
./configure --prefix=/usr --enable-shared --with-system-expat --with-ensurepip=install --without-static-libpython;
make
'''
package = '''
cd "Python-$version";
make DESTDIR="$pkgdir" install;
ln -sf python3 "$pkgdir/usr/bin/python"
'''
