[package]
name     = "libkexiv2"
version  = "26.04.2"
release  = 1
summary  = "KDE: Qt wrapper around Exiv2 image metadata"
homepage = "https://kde.org/plasma-desktop/"
license  = ["GPL-2.0-or-later"]
arch     = ["x86_64"]

depends     = ["exiv2", "qt6-base"]
makedepends = ["extra-cmake-modules", "cmake", "ninja", "python", "qt6-base", "qt6-declarative", "qt6-tools", "exiv2"]
options     = ["!lto"]

[[source]]
url    = "https://download.kde.org/stable/release-service/26.04.2/src/libkexiv2-26.04.2.tar.xz"
sha256 = "fdd8b2ca473339281676bccd1be1d6bf7df2f7644822c52a5cb73af8535a854e"

[steps]
build = '''
cmake -S "libkexiv2-$version" -B build -G Ninja -D CMAKE_BUILD_TYPE=Release -D CMAKE_INSTALL_PREFIX=/usr -D KDE_INSTALL_LIBDIR=lib -D KDE_INSTALL_LIBEXECDIR=lib -D KDE_INSTALL_USE_QT_SYS_PATHS=ON -D BUILD_TESTING=OFF -D BUILD_QCH=OFF -D BUILD_PYTHON_BINDINGS=OFF;
cmake --build build
'''
package = '''
DESTDIR="$pkgdir" cmake --install build
'''
