[package]
name     = "openssl"
version  = "3.4.6"
release  = 1
summary  = "TLS/SSL and crypto library"
homepage = "https://www.openssl.org/"
license  = ["Apache"]
arch     = ["x86_64"]

depends     = ["glibc", "zlib"]
makedepends = ["perl"]
provides    = ["libcrypto.so", "libssl.so"]

[[source]]
url    = "https://github.com/openssl/openssl/releases/download/openssl-3.4.6/openssl-3.4.6.tar.gz"
sha256 = "a57b8a1f09b502c904352c8a5386987675f2d6c52bc155f9a2f416faea1c0473"

[steps]
build = '''
cd "$name-$version";
./Configure --prefix=/usr --openssldir=/etc/ssl --libdir=lib shared zlib enable-ktls linux-x86_64;
make
'''
package = '''
cd "$name-$version";
make DESTDIR="$pkgdir" MANSUFFIX=ssl install_sw install_ssldirs
'''
