[package]
name     = "libunistring"
version  = "1.2"
release  = 1
summary  = "Library for manipulating Unicode strings and C strings"
homepage = "https://www.gnu.org/software/libunistring/"
license  = ["LGPL-3.0-or-later"]
arch     = ["x86_64"]

depends     = ["glibc"]

[[source]]
url    = "https://ftp.gnu.org/gnu/libunistring/libunistring-1.2.tar.gz"
sha256 = "fd6d5662fa706487c48349a758b57bc149ce94ec6c30624ec9fdc473ceabbc8e"

[steps]
build = '''
cd "$name-$version";
./configure --prefix=/usr --disable-static;
make
'''
package = '''
cd "$name-$version";
make DESTDIR="$pkgdir" install;
install -Dm644 COPYING.LIB "$pkgdir/usr/share/licenses/$name/COPYING.LIB"
'''
