[package]
name     = "sdl2"
version  = "2.30.9"
release  = 1
summary  = "Simple DirectMedia Layer — cross-platform multimedia library"
homepage = "https://www.libsdl.org/"
license  = ["Zlib"]
arch     = ["x86_64"]

depends     = ["glibc", "libx11", "libxext", "libxrandr", "libxcursor", "libxi", "wayland"]
makedepends = ["cmake", "ninja", "wayland", "wayland-protocols", "libx11", "libxext", "libxrandr", "libxcursor", "libxi", "mesa", "libgl"]
provides    = ["libSDL2-2.0.so"]

[[source]]
url    = "https://github.com/libsdl-org/SDL/releases/download/release-2.30.9/SDL2-2.30.9.tar.gz"
sha256 = "24b574f71c87a763f50704bbb630cbe38298d544a1f890f099a4696b1d6beba4"

[steps]
build = '''
cmake -B build -S "SDL2-$version" -G Ninja \
  -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release \
  -DSDL_STATIC=OFF -DSDL_SHARED=ON
cmake --build build
'''
package = '''
DESTDIR="$pkgdir" cmake --install build
'''
