[package]
name     = "karchive"
version  = "6.27.0"
release  = 1
summary  = "KDE: reading/writing archives (tar, zip, 7z, ar)"
homepage = "https://community.kde.org/Frameworks"
license  = ["LGPL-2.1-or-later"]
arch     = ["x86_64"]

depends     = ["qt6-base", "bzip2", "zlib", "xz", "zstd"]
makedepends = ["qt6-tools", "qt6-declarative", "extra-cmake-modules", "cmake", "ninja", "python", "qt6-base"]
options     = ["!lto"]

[[source]]
url    = "https://download.kde.org/stable/frameworks/6.27/karchive-6.27.0.tar.xz"
sha256 = "434edf78df8f4c9f25000d107ad1520d7ac14db580a202047bf19cbf77376522"

[steps]
build = '''
cmake -S "karchive-$version" -B build -G Ninja -D CMAKE_BUILD_TYPE=Release -D CMAKE_INSTALL_PREFIX=/usr -D KDE_INSTALL_LIBDIR=lib -D KDE_INSTALL_USE_QT_SYS_PATHS=ON -D BUILD_TESTING=OFF -D BUILD_QCH=OFF -D BUILD_PYTHON_BINDINGS=OFF;
cmake --build build
'''
package = '''
DESTDIR="$pkgdir" cmake --install build
'''
