[package]
name     = "fzf"
version  = "0.74.0"
release  = 1
summary  = "A command-line fuzzy finder"
homepage = "https://github.com/junegunn/fzf"
license  = ["MIT"]
arch     = ["x86_64"]

depends     = ["glibc"]
makedepends = ["go", "git"]

[[source]]
url    = "https://github.com/junegunn/fzf/archive/v0.74.0/fzf-0.74.0.tar.gz"
sha256 = "55ab5f2256edd8890f81d407b63d3a3e81cffe10e318cd196031dc85efdeb079"

[steps]
build = '''
cd "$name-$version";
export GOPATH="$srcdir/gopath" GOCACHE="$srcdir/gocache" GOFLAGS="-mod=mod" CGO_ENABLED=0;
go build -ldflags "-s -w -X main.version=0.74.0 -X main.revision=tarball" -o fzf .
'''
package = '''
cd "$name-$version";
install -Dm755 fzf "$pkgdir/usr/bin/fzf";
install -Dm755 bin/fzf-tmux "$pkgdir/usr/bin/fzf-tmux";
install -Dm644 man/man1/fzf.1 "$pkgdir/usr/share/man/man1/fzf.1";
install -Dm644 man/man1/fzf-tmux.1 "$pkgdir/usr/share/man/man1/fzf-tmux.1";
install -Dm644 shell/completion.bash "$pkgdir/usr/share/fzf/completion.bash";
install -Dm644 shell/key-bindings.bash "$pkgdir/usr/share/fzf/key-bindings.bash";
install -Dm644 shell/completion.zsh "$pkgdir/usr/share/fzf/completion.zsh";
install -Dm644 shell/key-bindings.zsh "$pkgdir/usr/share/fzf/key-bindings.zsh";
install -Dm644 LICENSE "$pkgdir/usr/share/licenses/$name/LICENSE"
'''
