[package]
name     = "mpdecimal"
version  = "4.0.0"
release  = 1
summary  = "Library for arbitrary precision correctly-rounded decimal arithmetic"
homepage = "https://www.bytereef.org/mpdecimal/"
license  = ["BSD-2-Clause"]
arch     = ["x86_64"]

depends     = ["glibc", "gcc-libs"]

[[source]]
url    = "https://www.bytereef.org/software/mpdecimal/releases/mpdecimal-4.0.0.tar.gz"
sha256 = "942445c3245b22730fd41a67a7c5c231d11cb1b9936b9c0f76334fb7d0b4468c"

[steps]
build = '''
cd "$name-$version";
./configure --prefix=/usr --disable-static;
make
'''
package = '''
cd "$name-$version";
make DESTDIR="$pkgdir" install;
install -Dm644 COPYRIGHT.txt "$pkgdir/usr/share/licenses/$name/COPYRIGHT.txt"
'''
