[package]
name     = "md4c"
version  = "0.5.2"
release  = 1
summary  = "C Markdown parser (Qt6 dep: libmd4c-html)"
homepage = "https://github.com/mity/md4c"
license  = ["MIT"]
arch     = ["x86_64"]

depends     = ["glibc"]
makedepends = ["cmake", "ninja"]
provides    = ["libmd4c.so", "libmd4c-html.so"]

[[source]]
url    = "https://github.com/mity/md4c/archive/refs/tags/release-0.5.2.tar.gz"
sha256 = "55d0111d48fb11883aaee91465e642b8b640775a4d6993c2d0e7a8092758ef21"

[steps]
build = '''
cmake -S "$name-release-$version" -B build -G Ninja -D CMAKE_BUILD_TYPE=Release -D CMAKE_INSTALL_PREFIX=/usr -D CMAKE_INSTALL_LIBDIR=lib -D BUILD_SHARED_LIBS=ON;
cmake --build build
'''
package = '''
DESTDIR="$pkgdir" cmake --install build;
install -Dm644 "$name-release-$version/LICENSE.md" "$pkgdir/usr/share/licenses/$name/LICENSE.md"
'''
