[package]
name     = "gmp"
version  = "6.3.0"
release  = 1
summary  = "GNU multiple precision arithmetic library (libgmp)"
homepage = "https://gmplib.org/"
license  = ["LGPL-3.0-or-later", "GPL-2.0-or-later"]
arch     = ["x86_64"]

depends     = ["glibc"]
provides    = ["libgmp.so", "libgmpxx.so"]

[[source]]
url    = "https://ftp.gnu.org/gnu/gmp/gmp-6.3.0.tar.xz"
sha256 = "a3c2b80201b89e68616f4ad30bc66aee4927c3ce50e33929ca819d5c43538898"

[steps]
build = '''
cd "$name-$version";
export CC="${CC:-gcc} -std=gnu17";
./configure --prefix=/usr --enable-cxx --enable-fat;
make
'''
package = '''
cd "$name-$version";
make DESTDIR="$pkgdir" install
'''
