[package]
name     = "sysstat"
version  = "12.7.6"
release  = 1
summary  = "System performance tools (sar, iostat, mpstat, pidstat)"
homepage = "https://github.com/sysstat/sysstat"
license  = ["GPL-2.0-or-later"]
arch     = ["x86_64"]

depends     = ["glibc"]

[[source]]
url    = "https://github.com/sysstat/sysstat/archive/refs/tags/v12.7.6.tar.gz"
sha256 = "dc77a08871f8e8813448ea31048833d4acbab7276dd9a456cd2526c008bd5301"

[steps]
build = '''
cd "$name-$version";
sa_lib_dir=/usr/lib/sa conf_dir=/etc ./configure --prefix=/usr --disable-sensors;
make
'''
package = '''
cd "$name-$version";
make DESTDIR="$pkgdir" install
'''
