[package]
name     = "systemsettings"
version  = "6.7.0"
release  = 1
summary  = "KDE: System Settings configuration center"
homepage = "https://kde.org/plasma-desktop/"
license  = ["GPL-2.0-or-later"]
arch     = ["x86_64"]

depends     = ["plasma-activities", "kauth", "kcmutils", "kcolorscheme", "kconfig", "kconfigwidgets", "kcoreaddons", "kcrash", "kdbusaddons", "ki18n", "kio", "kirigami", "kitemmodels", "kitemviews", "kjobwidgets", "krunner", "kservice", "kwidgetsaddons", "kwindowsystem", "kxmlgui", "qt6-base", "qt6-declarative"]
makedepends = ["kdoctools", "extra-cmake-modules", "cmake", "ninja", "python", "qt6-base", "qt6-declarative", "qt6-tools"]
options     = ["!lto"]

[[source]]
url    = "https://download.kde.org/stable/plasma/6.7.0/systemsettings-6.7.0.tar.xz"
sha256 = "59f24a45046b669d1ac16f80ee78323eb6f172130abac31c6d65cf61f05fa79f"

[steps]
build = '''
cmake -S "systemsettings-$version" -B build -G Ninja -D CMAKE_BUILD_TYPE=Release -D CMAKE_INSTALL_PREFIX=/usr -D KDE_INSTALL_LIBDIR=lib -D KDE_INSTALL_LIBEXECDIR=lib -D KDE_INSTALL_USE_QT_SYS_PATHS=ON -D BUILD_TESTING=OFF -D BUILD_QCH=OFF -D BUILD_PYTHON_BINDINGS=OFF;
cmake --build build
'''
package = '''
DESTDIR="$pkgdir" cmake --install build
'''
