[package]
name     = "gcc"
version  = "16.1.0"
release  = 2
summary  = "The GNU Compiler Collection (C and C++)"
homepage = "https://gcc.gnu.org/"
license  = ["GPL-3.0-or-later", "LGPL-3.0-or-later", "GFDL-1.3-or-later"]
arch     = ["x86_64"]

depends     = ["glibc", "binutils", "gmp", "mpfr", "mpc", "zlib", "linux-api-headers"]
options     = ["!lto"]

[[source]]
url    = "https://ftp.gnu.org/gnu/gcc/gcc-16.1.0/gcc-16.1.0.tar.xz"
sha256 = "50efb4d94c3397aff3b0d61a5abd748b4dd31d9d3f2ab7be05b171d36a510f79"

[steps]
build = '''
cd "$name-$version";
CFLAGS="${CFLAGS//-Werror=format-security/}";
CXXFLAGS="${CXXFLAGS//-Werror=format-security/}";
export CFLAGS CXXFLAGS;
mkdir -p ../build && cd ../build;
../"$name-$version"/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --enable-languages=c,c++ --enable-default-pie --enable-default-ssp --enable-__cxa_atexit --disable-multilib --disable-bootstrap --disable-werror --disable-nls --without-isl --with-system-zlib;
make
'''
package = '''
cd build;
make DESTDIR="$pkgdir" install;
ln -sf gcc "$pkgdir/usr/bin/cc";
rm -rf "$pkgdir"/usr/share/man/man7 "$pkgdir"/usr/share/info
'''
