[package]
name     = "libidn2"
version  = "2.3.7"
release  = 1
summary  = "Implementation of the IDNA2008, Punycode and TR46 specifications"
homepage = "https://www.gnu.org/software/libidn/"
license  = ["GPL-2.0-or-later OR LGPL-3.0-or-later"]
arch     = ["x86_64"]

depends     = ["glibc", "libunistring"]

[[source]]
url    = "https://ftp.gnu.org/gnu/libidn/libidn2-2.3.7.tar.gz"
sha256 = "4c21a791b610b9519b9d0e12b8097bf2f359b12f8dd92647611a929e6bfd7d64"

[steps]
build = '''
cd "$name-$version";
./configure --prefix=/usr --disable-static --disable-doc;
make
'''
package = '''
cd "$name-$version";
make DESTDIR="$pkgdir" install;
install -Dm644 COPYING "$pkgdir/usr/share/licenses/$name/COPYING"
'''
