[package]
name     = "libxslt"
version  = "1.1.42"
release  = 1
summary  = "XSLT processing library (libxslt + libexslt)"
homepage = "https://gitlab.gnome.org/GNOME/libxslt"
license  = ["MIT"]
arch     = ["x86_64"]

depends     = ["glibc", "libxml2", "libgcrypt", "libgpg-error"]
makedepends = ["pkgconf", "libgcrypt"]
provides    = ["libxslt.so", "libexslt.so"]

[[source]]
url    = "https://download.gnome.org/sources/libxslt/1.1/libxslt-1.1.42.tar.xz"
sha256 = "85ca62cac0d41fc77d3f6033da9df6fd73d20ea2fc18b0a3609ffb4110e1baeb"

[steps]
build = '''
cd "$name-$version"
./configure --prefix=/usr --disable-static --without-python
make
'''
package = '''
cd "$name-$version"
make DESTDIR="$pkgdir" install
'''
