[package]
name     = "pixman"
version  = "0.44.0"
release  = 1
summary  = "Low-level pixel manipulation library"
homepage = "https://pixman.org/"
license  = ["custom"]
arch     = ["x86_64"]

depends     = ["glibc"]
makedepends = ["meson", "ninja"]
provides    = ["libpixman-1.so"]

[[source]]
url    = "https://www.cairographics.org/releases/pixman-0.44.0.tar.gz"
sha256 = "89a4c1e1e45e0b23dffe708202cb2eaffde0fe3727d7692b2e1739fec78a7dac"

[steps]
build = '''
arch-meson "$name-$version" build -D libpng=disabled -D gtk=disabled -D tests=disabled -D demos=disabled -D loongson-mmi=disabled -D vmx=disabled -D arm-simd=disabled -D neon=disabled -D a64-neon=disabled -D mips-dspr2=disabled -D rvv=disabled;
meson compile -C build
'''
package = '''
meson install -C build --destdir "$pkgdir";
install -Dm644 "$name-$version/COPYING" "$pkgdir/usr/share/licenses/$name/COPYING"
'''
