[package]
name     = "qt6-speech"
version  = "6.11.1"
release  = 1
summary  = "Qt6 Text-to-Speech"
homepage = "https://blueberry.linux/"
license  = ["custom"]
arch     = ["x86_64"]

depends     = ["qt6-base", "qt6-declarative"]
makedepends = ["cmake", "ninja", "qt6-base", "qt6-declarative"]
options     = ["!lto"]

[[source]]
url    = "https://download.qt.io/official_releases/qt/6.11/6.11.1/submodules/qtspeech-everywhere-src-6.11.1.tar.xz"
sha256 = "c035c318012025875a653245701a23d3807e8e46b8bf7987877842219c273f14"

[steps]
build = '''
cmake -S "qtspeech-everywhere-src-6.11.1" -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_INSTALL_LIBDIR=lib -DQT_BUILD_EXAMPLES=OFF -DQT_BUILD_TESTS=OFF;
cmake --build build
'''
package = '''
DESTDIR="$pkgdir" cmake --install build
'''
