[package]
name     = "qt6-quick3d"
version  = "6.11.1"
release  = 1
summary  = "Qt 6 Quick 3D rendering module"
homepage = "https://www.qt.io/"
license  = ["LGPL-3.0-only"]
arch     = ["x86_64"]

depends     = ["qt6-base", "qt6-declarative", "qt6-shadertools", "assimp"]
makedepends = ["cmake", "ninja", "python", "qt6-base", "qt6-declarative", "perl", "qt6-shadertools", "assimp"]
options     = ["!lto"]

[[source]]
url    = "https://download.qt.io/official_releases/qt/6.11/6.11.1/submodules/qtquick3d-everywhere-src-6.11.1.tar.xz"
sha256 = "c76b85de3f8aa2a4bee64987acfef560675c1b378b92076c7c6264613e5b456f"

[steps]
build = '''
cmake -S "qtquick3d-everywhere-src-$version" -B build -G Ninja -D CMAKE_BUILD_TYPE=Release -D CMAKE_INSTALL_PREFIX=/usr -D INSTALL_LIBDIR=/usr/lib -D INSTALL_ARCHDATADIR=/usr/lib/qt6 -D QT_BUILD_EXAMPLES=OFF -D QT_BUILD_TESTS=OFF;
cmake --build build
'''
package = '''
DESTDIR="$pkgdir" cmake --install build
'''
