[package]
name     = "less"
version  = "668"
release  = 1
summary  = "Terminal pager — the default pager for git, man and friends"
homepage = "https://www.greenwoodsoftware.com/less/"
license  = ["GPL-3.0-or-later"]
arch     = ["x86_64"]

depends     = ["glibc", "ncurses"]

[[source]]
url    = "https://www.greenwoodsoftware.com/less/less-668.tar.gz"
sha256 = "2819f55564d86d542abbecafd82ff61e819a3eec967faa36cd3e68f1596a44b8"

[steps]
build = '''
cd "$name-$version";
./configure --prefix=/usr --sysconfdir=/etc --with-regex=posix;
make
'''
package = '''
cd "$name-$version";
make DESTDIR="$pkgdir" install;
install -Dm644 COPYING "$pkgdir/usr/share/licenses/$name/COPYING"
'''
