[package]
name     = "libpciaccess"
version  = "0.18.1"
release  = 1
summary  = "X11 library for PCI device access"
homepage = "https://gitlab.freedesktop.org/xorg/lib/libpciaccess"
license  = ["custom"]
arch     = ["x86_64"]

depends     = ["glibc"]
makedepends = ["meson", "ninja", "xorg-util-macros"]
provides    = ["libpciaccess.so"]

[[source]]
url    = "https://www.x.org/releases/individual/lib/libpciaccess-0.18.1.tar.xz"
sha256 = "4af43444b38adb5545d0ed1c2ce46d9608cc47b31c2387fc5181656765a6fa76"

[steps]
build = '''
arch-meson "$name-$version" build;
meson compile -C build
'''
package = '''
meson install -C build --destdir "$pkgdir";
install -Dm644 "$name-$version/COPYING" "$pkgdir/usr/share/licenses/$name/COPYING"
'''
