[package]
name     = "libplasma"
version  = "6.7.0"
release  = 1
summary  = "KDE: core Plasma framework (QML shell components)"
homepage = "https://kde.org/plasma-desktop/"
license  = ["GPL-2.0-or-later"]
arch     = ["x86_64"]

depends     = ["plasma-activities", "kcolorscheme", "kconfig", "kcoreaddons", "kglobalaccel", "kguiaddons", "ki18n", "kiconthemes", "kio", "kirigami", "knotifications", "kpackage", "ksvg", "kwidgetsaddons", "kwindowsystem", "libglvnd", "libx11", "libxcb", "qt6-5compat", "qt6-base", "qt6-declarative", "wayland"]
makedepends = ["kdoctools", "extra-cmake-modules", "cmake", "ninja", "python", "qt6-base", "qt6-declarative", "qt6-tools", "wayland-protocols", "plasma-wayland-protocols", "qt6-wayland"]
options     = ["!lto"]

[[source]]
url    = "https://download.kde.org/stable/plasma/6.7.0/libplasma-6.7.0.tar.xz"
sha256 = "8a85e4c9eb2c3c00b5683cce3aa2c949d06b956c88789c1b1c110b6abae20312"

[steps]
build = '''
cmake -S "libplasma-$version" -B build -G Ninja -D CMAKE_BUILD_TYPE=Release -D CMAKE_INSTALL_PREFIX=/usr -D KDE_INSTALL_LIBDIR=lib -D KDE_INSTALL_LIBEXECDIR=lib -D KDE_INSTALL_USE_QT_SYS_PATHS=ON -D BUILD_TESTING=OFF -D BUILD_QCH=OFF -D BUILD_PYTHON_BINDINGS=OFF;
cmake --build build
'''
package = '''
DESTDIR="$pkgdir" cmake --install build
'''
