[package]
name     = "jansson"
version  = "2.15.1"
release  = 1
summary  = "C library for encoding, decoding and manipulating JSON"
homepage = "https://github.com/akheron/jansson"
license  = ["MIT"]
arch     = ["x86_64"]

depends     = ["glibc"]
makedepends = ["pkgconf"]
provides    = ["libjansson.so"]

[[source]]
url    = "https://github.com/akheron/jansson/releases/download/v2.15.1/jansson-2.15.1.tar.gz"
sha256 = "0c7114dc0b2d22a670724a1f95922029d7077c19dbf79a584cb8084d2f267f2f"

[steps]
build = '''
cd "$name-$version"
./configure --prefix=/usr --disable-static
make
'''
package = '''
cd "$name-$version"
make DESTDIR="$pkgdir" install
'''
