[package]
name     = "libcap-ng"
version  = "0.8.5"
release  = 1
summary  = "Library for handling POSIX capabilities"
homepage = "https://people.redhat.com/sgrubb/libcap-ng/"
license  = ["LGPL-2.1-or-later"]
arch     = ["x86_64"]

depends     = ["glibc"]

[[source]]
url    = "https://people.redhat.com/sgrubb/libcap-ng/libcap-ng-0.8.5.tar.gz"
sha256 = "3ba5294d1cbdfa98afaacfbc00b6af9ed2b83e8a21817185dfd844cc8c7ac6ff"

[steps]
build = '''
cd "$name-$version";
./configure --prefix=/usr --disable-static --without-python --without-python3;
make
'''
package = '''
cd "$name-$version";
make DESTDIR="$pkgdir" install;
install -Dm644 COPYING.LIB "$pkgdir/usr/share/licenses/$name/COPYING.LIB"
'''
