[package]
name     = "keyutils"
version  = "1.6.3"
release  = 1
summary  = "Linux key management utilities (libkeyutils — krb5/gssapi)"
homepage = "https://www.kernel.org/"
license  = ["GPL-2.0-or-later", "LGPL-2.1-or-later"]
arch     = ["x86_64"]

depends     = ["glibc"]
options     = ["!lto"]

[[source]]
url    = "keyutils-1.6.3.tar.gz::https://git.kernel.org/pub/scm/linux/kernel/git/dhowells/keyutils.git/snapshot/keyutils-1.6.3.tar.gz"
sha256 = "a61d5706136ae4c05bd48f86186bcfdbd88dd8bd5107e3e195c924cfc1b39bb4"

[steps]
build = '''
cd "keyutils-$version";
make NO_ARLIB=1 LIBDIR=/usr/lib USRLIBDIR=/usr/lib BINDIR=/usr/bin SBINDIR=/usr/bin
'''
package = '''
cd "keyutils-$version";
make NO_ARLIB=1 LIBDIR=/usr/lib USRLIBDIR=/usr/lib BINDIR=/usr/bin SBINDIR=/usr/bin DESTDIR="$pkgdir" install
'''
