[package]
name     = "qqc2-desktop-style"
version  = "6.27.0"
release  = 1
summary  = "KDE: QtQuick Controls 2 desktop style"
homepage = "https://community.kde.org/Frameworks"
license  = ["LGPL-2.1-or-later"]
arch     = ["x86_64"]

depends     = ["qt6-base", "qt6-declarative", "kconfig", "kconfigwidgets", "kcoreaddons", "kiconthemes", "kirigami", "sonnet"]
makedepends = ["qt6-tools", "qt6-declarative", "extra-cmake-modules", "cmake", "ninja", "python", "qt6-base", "qt6-declarative"]
options     = ["!lto"]

[[source]]
url    = "https://download.kde.org/stable/frameworks/6.27/qqc2-desktop-style-6.27.0.tar.xz"
sha256 = "6c005f06c5f8c4ac349238abf14999bb917215a8f7b8c51364e2fdd12e9e6355"

[steps]
build = '''
cmake -S "qqc2-desktop-style-$version" -B build -G Ninja -D CMAKE_BUILD_TYPE=Release -D CMAKE_INSTALL_PREFIX=/usr -D KDE_INSTALL_LIBDIR=lib -D KDE_INSTALL_USE_QT_SYS_PATHS=ON -D BUILD_TESTING=OFF -D BUILD_QCH=OFF -D BUILD_PYTHON_BINDINGS=OFF;
cmake --build build
'''
package = '''
DESTDIR="$pkgdir" cmake --install build
'''
