[package]
name     = "xcb-util-keysyms"
version  = "0.4.1"
release  = 1
summary  = "XCB utility library: xcb-util-keysyms"
homepage = "https://xcb.freedesktop.org/"
license  = ["MIT"]
arch     = ["x86_64"]

depends     = ["libxcb"]
makedepends = ["xcb-proto", "xorgproto", "xorg-util-macros", "libxcb", "pkgconf", "gperf"]
provides    = ["libxcb-keysyms.so"]

[[source]]
url    = "https://xorg.freedesktop.org/archive/individual/lib/xcb-util-keysyms-0.4.1.tar.xz"
sha256 = "7c260a5294412aed429df1da2f8afd3bd07b7cba3fec772fba15a613a6d5c638"

[steps]
build = '''
cd "$name-$version";
./configure --prefix=/usr --disable-static;
make
'''
package = '''
cd "$name-$version";
make DESTDIR="$pkgdir" install;
install -Dm644 COPYING "$pkgdir/usr/share/licenses/$name/COPYING"
'''
