[package]
name     = "sudo"
version  = "1.9.16p2"
release  = 2
summary  = "Give certain users the ability to run some commands as root"
homepage = "https://www.sudo.ws/sudo/"
license  = ["custom"]
arch     = ["x86_64"]

depends     = ["glibc", "openssl"]

[[source]]
url    = "https://www.sudo.ws/dist/sudo-1.9.16p2.tar.gz"
sha256 = "976aa56d3e3b2a75593307864288addb748c9c136e25d95a9cc699aafa77239c"

[steps]
build = '''
cd "$name-$version";
./configure --prefix=/usr --sbindir=/usr/bin --libexecdir=/usr/lib --with-rundir=/run/sudo --with-vardir=/var/lib/sudo --without-pam --with-env-editor --with-secure-path;
make
'''
package = '''
cd "$name-$version";
make DESTDIR="$pkgdir" install;
install -dm755 "$pkgdir/etc";
printf '%%wheel ALL=(ALL:ALL) ALL\nroot ALL=(ALL:ALL) ALL\n' > "$pkgdir/etc/sudoers";
chmod 440 "$pkgdir/etc/sudoers"
'''
