[package]
name     = "libgpg-error"
version  = "1.51"
release  = 1
summary  = "Support library for libgcrypt"
homepage = "https://www.gnupg.org/"
license  = ["LGPL"]
arch     = ["x86_64"]

depends     = ["glibc"]
provides    = ["libgpg-error.so"]

[[source]]
url    = "https://gnupg.org/ftp/gcrypt/libgpg-error/libgpg-error-1.51.tar.bz2"
sha256 = "be0f1b2db6b93eed55369cdf79f19f72750c8c7c39fc20b577e724545427e6b2"

[steps]
build = '''
cd "$name-$version";
./configure --prefix=/usr --disable-static;
make
'''
package = '''
cd "$name-$version";
make DESTDIR="$pkgdir" install
'''
