[package]
name     = "libinput"
version  = "1.31.3"
release  = 1
summary  = "Input device library (KWin)"
homepage = "https://blueberry.linux/"
license  = ["custom"]
arch     = ["x86_64"]

depends     = ["glibc", "libevdev", "mtdev", "systemd", "libwacom"]
makedepends = ["meson", "ninja", "libevdev", "mtdev", "libwacom", "check", "doxygen"]
options     = ["!lto"]

[[source]]
url    = "https://gitlab.freedesktop.org/libinput/libinput/-/archive/1.31.3/libinput-1.31.3.tar.gz"
sha256 = "b6749bf6f1890f6631c0a70a027c35fec9d2e096a39f720548896e41474a9854"

[steps]
build = '''
function arch-meson () 
{ 
    meson setup "$@"
};
meson setup "libinput-1.31.3" build --prefix=/usr --buildtype=release -Dwerror=false -Ddocumentation=false -Dtests=false -Ddebug-gui=false;
meson compile -C build
'''
package = '''
meson install -C build --destdir "$pkgdir"
'''
