[package]
name     = "libtool"
version  = "2.5.4"
release  = 1
summary  = "GNU generic library support script (libtool + libltdl)"
homepage = "https://www.gnu.org/software/libtool/"
license  = ["GPL-3.0-or-later"]
arch     = ["x86_64"]

depends     = ["glibc", "bash", "m4", "tar"]
provides    = ["libltdl.so"]
makedepends = ["m4", "make", "gcc"]

[[source]]
url    = "https://ftp.gnu.org/gnu/libtool/libtool-2.5.4.tar.xz"
sha256 = "f81f5860666b0bc7d84baddefa60d1cb9fa6fceb2398cc3baca6afaa60266675"

[steps]
build = '''
cd "$name-$version";
./configure --prefix=/usr;
make
'''
package = '''
cd "$name-$version";
make DESTDIR="$pkgdir" install
'''
