[package]
name     = "glibc"
version  = "2.43"
release  = 1
summary  = "GNU C Library — headers, startup objects, and libraries (on-device SDK)"
homepage = "https://www.gnu.org/software/libc/"
license  = ["GPL-2.0-or-later", "LGPL-2.1-or-later"]
arch     = ["x86_64"]

depends     = ["linux-api-headers"]
makedepends = ["linux-api-headers", "python"]
options     = ["staticlibs", "!lto"]

[[source]]
url    = "https://ftp.gnu.org/gnu/glibc/glibc-2.43.tar.xz"
sha256 = "d9c86c6b5dbddb43a3e08270c5844fc5177d19442cf5b8df4be7c07cd5fa3831"

[steps]
build = '''
CFLAGS="${CFLAGS//-Wp,-D_FORTIFY_SOURCE=3/}";
CFLAGS="${CFLAGS//-Werror=format-security/}";
export CFLAGS;
mkdir -p build && cd build;
../"glibc-$version"/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --with-headers=/usr/include --enable-kernel=5.4 --enable-cet --enable-bind-now --enable-stack-protector=strong --disable-profile --disable-werror --without-selinux --disable-nscd;
make
'''
package = '''
cd build;
make install_root="$pkgdir" install;
rm -rf "$pkgdir/usr/share/info" "$pkgdir/usr/share/man" "$pkgdir/usr/share/locale"
'''
