[package]
name     = "libcap"
version  = "2.78"
release  = 1
summary  = "POSIX 1003.1e capabilities library"
homepage = "https://sites.google.com/site/fullycapable/"
license  = ["GPL2"]
arch     = ["x86_64"]

depends     = ["glibc"]
provides    = ["libcap.so", "libpsx.so"]

[[source]]
url    = "https://www.kernel.org/pub/linux/libs/security/linux-privs/libcap2/libcap-2.78.tar.xz"
sha256 = "0d621e562fd932ccf67b9660fb018e468a683d7b827541df27813228c996bb11"

[steps]
build = '''
cd "$name-$version";
make CC=gcc GO= prefix=/usr lib=lib PAM_CAP=no
'''
package = '''
cd "$name-$version";
make install DESTDIR="$pkgdir" prefix=/usr lib=lib PAM_CAP=no RAISE_SETFCAP=no GO=;
install -Dm644 License "$pkgdir/usr/share/licenses/$name/License"
'''
