# fstab.conf — mount options written to the target's /etc/fstab.
---
mountOptions:
    default:  defaults,relatime
    btrfs:    defaults,relatime,compress=zstd
ssdExtraMountOptions:
    ext4:  discard
    btrfs: discard,compress=zstd
crypttabOptions: luks
