# partition.conf — partitioning defaults for Blueberry Desktop.
---
efiSystemPartition:     "/boot/efi"
efiSystemPartitionSize: 512M
userSwapChoices:
  - none
  - small
  - suspend
drawNestedPartitions:   false
alwaysShowPartitionLabels: true
defaultFileSystemType:  "ext4"
availableFileSystemTypes: [ "ext4", "btrfs", "xfs" ]
initialPartitioningChoice: erase
initialSwapChoice:      small
