# users.conf — account creation on the target.
---
defaultGroups:
    - wheel
    - audio
    - video
    - network
    - storage
    - input
autologinGroup:  autologin
sudoersGroup:    wheel
setRootPassword:  true
doReusePassword:  true
availableShells:  /bin/bash, /bin/sh
avatarFilePath:   ~/.face
passwordRequirements:
    minLength: 1
    maxLength: -1
userShell:        /bin/bash
