[package]
name     = "kdeplasma-addons"
version  = "6.7.0"
release  = 1
summary  = "KDE: extra Plasma widgets, wallpapers, and runners"
homepage = "https://kde.org/plasma-desktop/"
license  = ["GPL-2.0-or-later"]
arch     = ["x86_64"]

depends     = ["icu", "kauth", "kcmutils", "kconfig", "kcoreaddons", "kdbusaddons", "kdeclarative", "kglobalaccel", "kguiaddons", "kholidays", "ki18n", "kiconthemes", "kio", "kirigami", "kirigami-addons", "kitemmodels", "kjobwidgets", "knewstuff", "knotifications", "kpackage", "krunner", "kservice", "ksvg", "kunitconversion", "kwidgetsaddons", "kwin", "kwindowsystem", "kxmlgui", "libplasma", "plasma-workspace", "qt6-5compat", "qt6-base", "qt6-declarative", "qt6-quick3d", "sonnet"]
makedepends = ["kdoctools", "extra-cmake-modules", "cmake", "ninja", "python", "qt6-base", "qt6-declarative", "qt6-tools", "qt6-quick3d", "corrosion", "rust"]
options     = ["!lto"]

[[source]]
url    = "https://download.kde.org/stable/plasma/6.7.0/kdeplasma-addons-6.7.0.tar.xz"
sha256 = "8b86b0b79b0af2da097d81dce099913d43574e08c4428a7925870692178b4298"

[steps]
build = '''
cmake -S "kdeplasma-addons-$version" -B build -G Ninja -D CMAKE_BUILD_TYPE=Release -D CMAKE_INSTALL_PREFIX=/usr -D KDE_INSTALL_LIBDIR=lib -D KDE_INSTALL_LIBEXECDIR=lib -D KDE_INSTALL_USE_QT_SYS_PATHS=ON -D BUILD_TESTING=OFF -D BUILD_QCH=OFF -D BUILD_PYTHON_BINDINGS=OFF;
cmake --build build
'''
package = '''
DESTDIR="$pkgdir" cmake --install build
'''
