[package]
name     = "binutils"
version  = "2.47"
release  = 1
summary  = "GNU assembler, linker and binary utilities (as, ld, ar, objdump, ...)"
homepage = "https://www.gnu.org/software/binutils/"
license  = ["GPL-3.0-or-later", "LGPL-3.0-or-later"]
arch     = ["x86_64"]

depends     = ["glibc", "zlib", "elfutils", "flex"]

[[source]]
url    = "https://ftp.gnu.org/gnu/binutils/binutils-2.47.tar.xz"
sha256 = "154ab23b60070e8f27013c22977f1129425d67d1e8acd6e13010e617811e4cff"

[steps]
build = '''
mkdir -p build && cd build;
../"$name-$version"/configure --prefix=/usr --with-system-zlib --enable-deterministic-archives --enable-default-hash-style=gnu --disable-multilib --disable-werror --disable-gprofng --disable-nls;
make
'''
package = '''
cd build;
make DESTDIR="$pkgdir" install;
rm -f "$pkgdir"/usr/share/man/man1/{dlltool,nlmconv,windmc,windres}* 2> /dev/null || true
'''
