[package]
name     = "kdoctools"
version  = "6.27.0"
release  = 1
summary  = "KDE: documentation generation from DocBook"
homepage = "https://community.kde.org/Frameworks"
license  = ["LGPL-2.1-or-later"]
arch     = ["x86_64"]

depends     = ["qt6-base", "karchive", "ki18n", "docbook-xsl", "docbook-xml"]
makedepends = ["qt6-tools", "qt6-declarative", "extra-cmake-modules", "cmake", "ninja", "python", "qt6-base", "docbook-xsl", "docbook-xml", "libxslt", "perl-uri"]
options     = ["!lto"]

[[source]]
url    = "https://download.kde.org/stable/frameworks/6.27/kdoctools-6.27.0.tar.xz"
sha256 = "69026ef8607cb6257e4d1f0e46e451130ef7ba67994a83e4f9a6c46eefd5a3f3"

[steps]
build = '''
cmake -S "kdoctools-$version" -B build -G Ninja -D CMAKE_BUILD_TYPE=Release -D CMAKE_INSTALL_PREFIX=/usr -D KDE_INSTALL_LIBDIR=lib -D KDE_INSTALL_USE_QT_SYS_PATHS=ON -D BUILD_TESTING=OFF -D BUILD_QCH=OFF -D BUILD_PYTHON_BINDINGS=OFF;
cmake --build build
'''
package = '''
DESTDIR="$pkgdir" cmake --install build
'''
