[package]
name     = "openssh"
version  = "10.5p1"
release  = 1
summary  = "OpenSSH — full SSH server and client suite"
homepage = "https://www.openssh.com/"
license  = ["BSD-2-Clause"]
arch     = ["x86_64"]

depends     = ["glibc", "openssl", "zlib", "libxcrypt"]
# user-editable config — preserved across upgrades (bpm writes a .bpmnew instead)
backup      = ["etc/ssh/sshd_config", "etc/ssh/ssh_config"]

[upstream]
url   = "https://cdn.openbsd.org/pub/OpenBSD/OpenSSH/portable/"
regex = "openssh-([0-9.]+p[0-9]+)\\.tar"

[[source]]
url    = "https://cdn.openbsd.org/pub/OpenBSD/OpenSSH/portable/openssh-10.5p1.tar.gz"
sha256 = "d44d28a839ea9daf969cc69150fde59910b2b39361dad81a3bd6cbd19218db11"

[steps]
build = '''
cd "$name-$version";
./configure --prefix=/usr --sysconfdir=/etc/ssh --with-privsep-path=/var/empty --with-privsep-user=nobody --without-pam --with-ssl-engine --with-zlib;
make
'''
package = '''
cd "$name-$version";
make DESTDIR="$pkgdir" install
'''
