[package]
name     = "pcre2"
version  = "10.47"
release  = 1
summary  = "Perl Compatible Regular Expressions v2"
homepage = "https://github.com/PCRE2Project/pcre2"
license  = ["BSD-3-Clause"]
arch     = ["x86_64"]

depends     = ["glibc", "zlib", "bzip2"]
provides    = ["libpcre2-8.so", "libpcre2-16.so", "libpcre2-32.so"]

[[source]]
url    = "https://github.com/PCRE2Project/pcre2/releases/download/pcre2-10.47/pcre2-10.47.tar.bz2"
sha256 = "47fe8c99461250d42f89e6e8fdaeba9da057855d06eb7fc08d9ca03fd08d7bc7"

[steps]
build = '''
cd "$name-$version";
./configure --prefix=/usr --enable-jit --enable-pcre2-16 --enable-pcre2-32 --enable-pcre2grep-libz --enable-pcre2grep-libbz2 --disable-static;
make
'''
package = '''
cd "$name-$version";
make DESTDIR="$pkgdir" install
'''
