[package]
name     = "strace"
version  = "7.1"
release  = 1
summary  = "A diagnostic, debugging and instructional userspace tracer"
homepage = "https://strace.io/"
license  = ["LGPL-2.1-or-later"]
arch     = ["x86_64"]

depends     = ["glibc", "elfutils", "ncurses"]
options     = ["!lto"]

[[source]]
url    = "https://github.com/strace/strace/releases/download/v7.1/strace-7.1.tar.xz"
sha256 = "81743ecf2a5b44186b2f5038afdc8beda7e5c70aed15b4fbfbcc6e9ece24490f"

[steps]
build = '''
cd "$name-$version";
./configure --prefix=/usr --enable-mpers=check --enable-bundled=yes --disable-gcc-Werror;
make
'''
package = '''
cd "$name-$version";
make DESTDIR="$pkgdir" install
'''
