[package]
name     = "bash-completion"
version  = "2.14.0"
release  = 1
summary  = "Programmable completion for the bash shell"
homepage = "https://github.com/scop/bash-completion"
license  = ["GPL-2.0-or-later"]
arch     = ["x86_64"]

depends     = ["bash"]
makedepends = ["make", "gcc", "pkgconf"]

[[source]]
url    = "https://github.com/scop/bash-completion/releases/download/2.14.0/bash-completion-2.14.0.tar.xz"
sha256 = "5c7494f968280832d6adb5aa19f745a56f1a79df311e59338c5efa6f7285e168"

[steps]
build = '''
cd "$name-$version"
./configure --prefix=/usr
make -j"$(nproc)"
'''
package = '''
cd "$name-$version"
make DESTDIR="$pkgdir" install
install -Dm644 COPYING "$pkgdir/usr/share/licenses/$name/COPYING"
'''
