[package]
name     = "fontconfig"
version  = "2.15.0"
release  = 1
summary  = "Library for configuring and customizing font access"
homepage = "https://www.freedesktop.org/wiki/Software/fontconfig/"
license  = ["custom"]
arch     = ["x86_64"]

depends     = ["expat", "freetype2", "glibc"]
makedepends = ["meson", "ninja", "gperf", "python"]
provides    = ["libfontconfig.so"]

[[source]]
url    = "https://www.freedesktop.org/software/fontconfig/release/fontconfig-2.15.0.tar.xz"
sha256 = "63a0658d0e06e0fa886106452b58ef04f21f58202ea02a94c39de0d3335d7c0e"

[steps]
build = '''
arch-meson "$name-$version" build -D doc=disabled -D tests=disabled -D nls=disabled;
meson compile -C build
'''
package = '''
meson install -C build --destdir "$pkgdir";
install -Dm644 "$name-$version/COPYING" "$pkgdir/usr/share/licenses/$name/COPYING"
'''
