[package]
name     = "hunspell"
version  = "1.7.2"
release  = 1
summary  = "Spell checker and morphological analyzer library"
homepage = "https://hunspell.github.io/"
license  = ["LGPL-2.1-or-later", "GPL-2.0-or-later", "MPL-1.1"]
arch     = ["x86_64"]

depends     = ["glibc", "gcc-libs", "readline"]
makedepends = ["autoconf", "automake", "libtool", "gettext", "pkgconf"]
provides    = ["libhunspell-1.7.so"]

[[source]]
url    = "https://github.com/hunspell/hunspell/releases/download/v1.7.2/hunspell-1.7.2.tar.gz"
sha256 = "11ddfa39afe28c28539fe65fc4f1592d410c1e9b6dd7d8a91ca25d85e9ec65b8"

[steps]
build = '''
cd "$name-$version"
autoreconf -vfi
./configure --prefix=/usr --disable-static --with-ui --with-readline
make
'''
package = '''
cd "$name-$version"
make DESTDIR="$pkgdir" install
'''
