[package]
name     = "acl"
version  = "2.3.2"
release  = 1
summary  = "Access control list utilities, libraries and headers"
homepage = "https://savannah.nongnu.org/projects/acl"
license  = ["LGPL"]
arch     = ["x86_64"]

depends     = ["glibc", "attr"]
provides    = ["libacl.so"]

[[source]]
url    = "https://download.savannah.nongnu.org/releases/acl/acl-2.3.2.tar.gz"
sha256 = "5f2bdbad629707aa7d85c623f994aa8a1d2dec55a73de5205bac0bf6058a2f7c"

[steps]
build = '''
cd "$name-$version";
./configure --prefix=/usr --disable-static;
make
'''
package = '''
cd "$name-$version";
make DESTDIR="$pkgdir" install
'''
