[package]
name     = "qqc2-breeze-style"
version  = "6.7.0"
release  = 1
summary  = "KDE: Breeze style for QtQuick Controls 2"
homepage = "https://kde.org/plasma-desktop/"
license  = ["GPL-2.0-or-later"]
arch     = ["x86_64"]

depends     = ["kcolorscheme", "kconfig", "kguiaddons", "kiconthemes", "kirigami", "qt6-base", "qt6-declarative"]
makedepends = ["kdoctools", "extra-cmake-modules", "cmake", "ninja", "python", "qt6-base", "qt6-declarative", "qt6-tools"]
options     = ["!lto"]

[[source]]
url    = "https://download.kde.org/stable/plasma/6.7.0/qqc2-breeze-style-6.7.0.tar.xz"
sha256 = "81fb0f43fe15c2bcd1c62e742caba84d60a4eb9380c0bcec447b5b7728e29fbb"

[steps]
build = '''
cmake -S "qqc2-breeze-style-$version" -B build -G Ninja -D CMAKE_BUILD_TYPE=Release -D CMAKE_INSTALL_PREFIX=/usr -D KDE_INSTALL_LIBDIR=lib -D KDE_INSTALL_LIBEXECDIR=lib -D KDE_INSTALL_USE_QT_SYS_PATHS=ON -D BUILD_TESTING=OFF -D BUILD_QCH=OFF -D BUILD_PYTHON_BINDINGS=OFF;
cmake --build build
'''
package = '''
DESTDIR="$pkgdir" cmake --install build
'''
