[package]
name     = "kde-cli-tools"
version  = "6.7.0"
release  = 1
summary  = "KDE: command-line tools for the Plasma workspace"
homepage = "https://kde.org/plasma-desktop/"
license  = ["GPL-2.0-or-later"]
arch     = ["x86_64"]

depends     = ["kcmutils", "kcompletion", "kconfig", "kcoreaddons", "kdesu", "ki18n", "kiconthemes", "kio", "kparts", "kservice", "kwidgetsaddons", "kwindowsystem", "qt6-base", "qt6-svg"]
makedepends = ["kdoctools", "extra-cmake-modules", "cmake", "ninja", "python", "qt6-base", "qt6-declarative", "qt6-tools"]
options     = ["!lto"]

[[source]]
url    = "https://download.kde.org/stable/plasma/6.7.0/kde-cli-tools-6.7.0.tar.xz"
sha256 = "2720ff7efbf97bef469b02f54489f3d9b2a0b98c871aedb915acdbaf99f31998"

[steps]
build = '''
cmake -S "kde-cli-tools-$version" -B build -G Ninja -D CMAKE_BUILD_TYPE=Release -D CMAKE_INSTALL_PREFIX=/usr -D KDE_INSTALL_LIBDIR=lib -D KDE_INSTALL_LIBEXECDIR=lib -D KDE_INSTALL_USE_QT_SYS_PATHS=ON -D BUILD_TESTING=OFF -D BUILD_QCH=OFF -D BUILD_PYTHON_BINDINGS=OFF;
cmake --build build
'''
package = '''
DESTDIR="$pkgdir" cmake --install build
'''
