[package]
name     = "htop"
version  = "3.5.2"
release  = 1
summary  = "Interactive process viewer"
homepage = "https://htop.dev/"
license  = ["GPL-2.0-or-later"]
arch     = ["x86_64"]

depends     = ["glibc", "ncurses", "libcap"]

[[source]]
url    = "https://github.com/htop-dev/htop/releases/download/3.5.2/htop-3.5.2.tar.xz"
sha256 = "225128e697c4a8c8a878fd0078c965ff8bd5fb24913bfc8473b8edbd50f843f8"

[steps]
build = '''
cd "$name-$version";
./configure --prefix=/usr --sysconfdir=/etc --enable-unicode --enable-affinity --enable-capabilities --disable-delayacct --disable-unwind;
make
'''
package = '''
cd "$name-$version";
make DESTDIR="$pkgdir" install;
install -Dm644 COPYING "$pkgdir/usr/share/licenses/$name/COPYING"
'''
