[package]
name     = "htop"
version  = "3.5.3"
release  = 1
summary  = "Interactive process viewer"
homepage = "https://htop.dev/"
license  = ["GPL-2.0-or-later"]
arch     = ["x86_64"]

depends     = ["glibc", "ncurses", "libcap"]

[[source]]
url    = "https://github.com/htop-dev/htop/releases/download/3.5.3/htop-3.5.3.tar.xz"
sha256 = "a8b164386494cb85bb255a415a3f5f80afe7a0c4491da5d113b3a0f951087e65"

[steps]
build = '''
cd "$name-$version";
./configure --prefix=/usr --sysconfdir=/etc --enable-unicode --enable-affinity --enable-capabilities --disable-delayacct --disable-unwind;
make
'''
package = '''
cd "$name-$version";
make DESTDIR="$pkgdir" install;
install -Dm644 COPYING "$pkgdir/usr/share/licenses/$name/COPYING"
'''
