[package]
name     = "readline"
version  = "8.2"
release  = 1
summary  = "GNU library for command-line editing and history"
homepage = "https://tiswww.case.edu/php/chet/readline/rltop.html"
license  = ["GPL-3.0-or-later"]
arch     = ["x86_64"]

depends     = ["glibc", "ncurses"]

[[source]]
url    = "https://ftp.gnu.org/gnu/readline/readline-8.2.tar.gz"
sha256 = "3feb7171f16a84ee82ca18a36d7b9be109a52c04f492a053331d7d1095007c35"

[steps]
build = '''
cd "$name-$version";
./configure --prefix=/usr --disable-static;
make SHLIB_LIBS=-lncursesw
'''
package = '''
cd "$name-$version";
make DESTDIR="$pkgdir" install;
install -Dm644 COPYING "$pkgdir/usr/share/licenses/$name/COPYING"
'''
