[package]
name     = "readline"
version  = "8.3"
release  = 1
summary  = "GNU library for command-line editing and history"
homepage = "https://tiswww.case.edu/php/chet/readline/rltop.html"
license  = ["GPL-3.0-or-later"]
arch     = ["x86_64"]

depends     = ["glibc", "ncurses"]

[[source]]
url    = "https://ftp.gnu.org/gnu/readline/readline-8.3.tar.gz"
sha256 = "fe5383204467828cd495ee8d1d3c037a7eba1389c22bc6a041f627976f9061cc"

[steps]
build = '''
cd "$name-$version";
./configure --prefix=/usr --disable-static;
make SHLIB_LIBS=-lncursesw
'''
package = '''
cd "$name-$version";
make DESTDIR="$pkgdir" install;
install -Dm644 COPYING "$pkgdir/usr/share/licenses/$name/COPYING"
'''
