[package]
name     = "konsole"
version  = "26.04.2"
release  = 1
summary  = "KDE: the Konsole terminal emulator"
homepage = "https://kde.org/plasma-desktop/"
license  = ["GPL-2.0-or-later"]
arch     = ["x86_64"]

depends     = ["icu", "kbookmarks", "kcolorscheme", "kconfig", "kconfigwidgets", "kcoreaddons", "kcrash", "kdbusaddons", "kglobalaccel", "kguiaddons", "ki18n", "kiconthemes", "kio", "knewstuff", "knotifications", "knotifyconfig", "kparts", "kpty", "kservice", "ktextwidgets", "kwidgetsaddons", "kwindowsystem", "kxmlgui", "libxkbcommon", "qt6-base", "qt6-multimedia"]
makedepends = ["extra-cmake-modules", "cmake", "ninja", "python", "qt6-base", "qt6-declarative", "qt6-tools", "qt6-multimedia"]
options     = ["!lto"]

[[source]]
url    = "https://download.kde.org/stable/release-service/26.04.2/src/konsole-26.04.2.tar.xz"
sha256 = "d81a696d6a316d0c8fabe3cecd83783f656ee97c70ced89513b3fd16e9d216ac"

[steps]
build = '''
cmake -S "konsole-$version" -B build -G Ninja -D CMAKE_BUILD_TYPE=Release -D CMAKE_INSTALL_PREFIX=/usr -D KDE_INSTALL_LIBDIR=lib -D KDE_INSTALL_LIBEXECDIR=lib -D KDE_INSTALL_USE_QT_SYS_PATHS=ON -D BUILD_TESTING=OFF -D BUILD_QCH=OFF -D BUILD_PYTHON_BINDINGS=OFF;
cmake --build build
'''
package = '''
DESTDIR="$pkgdir" cmake --install build
'''
