[package]
name     = "libaio"
version  = "0.3.113"
release  = 1
summary  = "Asynchronous I/O library"
homepage = "https://pagure.io/libaio"
license  = ["LGPL-2.1-or-later"]
arch     = ["x86_64"]

depends     = ["glibc"]
provides    = ["libaio.so"]
options     = ["!lto"]

[[source]]
url    = "https://releases.pagure.org/libaio/libaio-0.3.113.tar.gz"
sha256 = "2c44d1c5fd0d43752287c9ae1eb9c023f04ef848ea8d4aafa46e9aedb678200b"

[steps]
build = '''
cd "$name-$version";
make prefix=/usr
'''
package = '''
cd "$name-$version";
make prefix=/usr DESTDIR="$pkgdir" install
'''
