[package]
name     = "libnl"
version  = "3.11.0"
release  = 1
summary  = "Library for applications dealing with netlink sockets"
homepage = "https://github.com/thom311/libnl"
license  = ["LGPL-2.1-only"]
arch     = ["x86_64"]

depends     = ["glibc"]
makedepends = ["flex", "bison", "pkgconf"]
provides    = ["libnl-3.so", "libnl-route-3.so", "libnl-genl-3.so", "libnl-nf-3.so", "libnl-cli-3.so", "libnl-idiag-3.so", "libnl-xfrm-3.so"]

[[source]]
url    = "https://github.com/thom311/libnl/releases/download/libnl3_11_0/libnl-3.11.0.tar.gz"
sha256 = "2a56e1edefa3e68a7c00879496736fdbf62fc94ed3232c0baba127ecfa76874d"

[steps]
build = '''
cd "$name-$version"
./configure --prefix=/usr --sysconfdir=/etc --disable-static
make
'''
package = '''
cd "$name-$version"
make DESTDIR="$pkgdir" install
'''
