[package]
name     = "nginx"
version  = "1.26.3"
release  = 2
summary  = "Lightweight HTTP server and IMAP/POP3 proxy server"
homepage = "https://nginx.org/"
license  = ["BSD-2-Clause"]
arch     = ["x86_64"]

depends     = ["glibc", "pcre2", "zlib", "openssl"]

[[source]]
url    = "https://nginx.org/download/nginx-1.26.3.tar.gz"
sha256 = "69ee2b237744036e61d24b836668aad3040dda461fe6f570f1787eab570c75aa"

[steps]
build = '''
cd "$name-$version";
./configure --prefix=/etc/nginx --sbin-path=/usr/bin/nginx --conf-path=/etc/nginx/nginx.conf --pid-path=/run/nginx.pid --lock-path=/run/lock/nginx.lock --http-log-path=/var/log/nginx/access.log --error-log-path=/var/log/nginx/error.log --http-client-body-temp-path=/var/lib/nginx/client-body --http-proxy-temp-path=/var/lib/nginx/proxy --with-http_ssl_module --with-http_v2_module --with-http_gzip_static_module --with-http_realip_module --with-http_stub_status_module --with-pcre-jit --with-threads --with-file-aio;
make
'''
package = '''
cd "$name-$version";
make DESTDIR="$pkgdir" install;
rm -rf "$pkgdir/run";
install -dm755 "$pkgdir/etc/sv/nginx";
printf '#!/bin/sh\nexec /usr/bin/nginx -g "daemon off;"\n' > "$pkgdir/etc/sv/nginx/run";
chmod 755 "$pkgdir/etc/sv/nginx/run"
'''
