[package]
name     = "mpfr"
version  = "4.2.1"
release  = 1
summary  = "Multiple-precision floating-point library (libmpfr)"
homepage = "https://www.mpfr.org/"
license  = ["LGPL-3.0-or-later"]
arch     = ["x86_64"]

depends     = ["gmp"]
provides    = ["libmpfr.so"]

[[source]]
url    = "https://www.mpfr.org/mpfr-4.2.1/mpfr-4.2.1.tar.xz"
sha256 = "277807353a6726978996945af13e52829e3abd7a9a5b7fb2793894e18f1fcbb2"

[steps]
build = '''
cd "$name-$version";
./configure --prefix=/usr --enable-thread-safe;
make
'''
package = '''
cd "$name-$version";
make DESTDIR="$pkgdir" install
'''
