[package]
name     = "lsof"
version  = "4.99.7"
release  = 1
summary  = "Lists information about files opened by processes (ports, sockets, files)"
homepage = "https://github.com/lsof-org/lsof"
license  = ["custom:lsof"]
arch     = ["x86_64"]

depends     = ["glibc"]
makedepends = ["make", "gcc", "autoconf", "automake", "pkgconf"]

[[source]]
url    = "https://github.com/lsof-org/lsof/releases/download/4.99.7/lsof-4.99.7.tar.gz"
sha256 = "4a10391aab0b8ce1f539e82a1966693b2a6cf225972a6504ebb7ec4fa71675de"

[steps]
build = '''
cd "$name-$version"
./configure --prefix=/usr
make -j"$(nproc)"
'''
package = '''
cd "$name-$version"
make DESTDIR="$pkgdir" install
install -Dm644 COPYING "$pkgdir/usr/share/licenses/$name/COPYING"
'''
