[package]
name     = "libgcrypt"
version  = "1.12.2"
release  = 1
summary  = "General purpose cryptographic library"
homepage = "https://www.gnupg.org/"
license  = ["LGPL"]
arch     = ["x86_64"]

depends     = ["glibc", "libgpg-error"]
provides    = ["libgcrypt.so"]

[[source]]
url    = "https://gnupg.org/ftp/gcrypt/libgcrypt/libgcrypt-1.12.2.tar.bz2"
sha256 = "7ce33c2492221a0436f96a8500215e9f3e3dcb5fd26a757cd415e7a843babd5e"

[steps]
build = '''
cd "$name-$version";
./configure --prefix=/usr --disable-static;
make
'''
package = '''
cd "$name-$version";
make DESTDIR="$pkgdir" install
'''
