[package]
name     = "aardvark-dns"
version  = "2.1.0"
release  = 1
summary  = "Authoritative DNS server for container names (netavark companion)"
homepage = "https://github.com/containers/aardvark-dns"
license  = ["Apache-2.0"]
arch     = ["x86_64"]

depends     = ["glibc", "gcc-libs"]
makedepends = ["rust", "git"]

[[source]]
url    = "https://github.com/containers/aardvark-dns/archive/v2.1.0/aardvark-dns-2.1.0.tar.gz"
sha256 = "daf871488603e659b0501224cf0731ac317809b1d1701fc061cb4f6ae39a894f"

[steps]
build = '''
cd "aardvark-dns-$version"
export CARGO_HOME="$srcdir/cargo"
cargo build --release
'''
package = '''
cd "aardvark-dns-$version"
install -Dm755 target/release/aardvark-dns "$pkgdir/usr/lib/podman/aardvark-dns"
'''
