services:
  recipe-hub:
    build: .
    image: blueberry-recipe-hub
    container_name: blueberry-recipe-hub
    ports:
      - "8000:8000"
    volumes:
      - bbrecipes:/data
    restart: unless-stopped

volumes:
  bbrecipes:
