[package]
name     = "p7zip"
version  = "17.06"
release  = 1
summary  = "Command-line port of 7-Zip, a file archiver with a high compression ratio"
homepage = "https://github.com/p7zip-project/p7zip"
license  = ["LGPL-2.1-or-later", "custom:unRAR"]
arch     = ["x86_64"]

depends     = ["glibc", "gcc-libs"]
makedepends = []

[[source]]
url    = "https://github.com/p7zip-project/p7zip/archive/v17.06/p7zip-17.06.tar.gz"
sha256 = "c35640020e8f044b425d9c18e1808ff9206dc7caf77c9720f57eb0849d714cd1"

[steps]
build = '''
cd "$name-$version";
cp makefile.linux_amd64 makefile.machine;
make all3
'''
package = '''
cd "$name-$version";
# install.sh args: <bindir> <sharedir> <mandir> <docdir> <destdir>
sh install.sh /usr/bin /usr/lib/p7zip /usr/share/man /usr/share/doc/p7zip "$pkgdir";
install -Dm644 DOC/License.txt "$pkgdir/usr/share/licenses/$name/License.txt";
install -Dm644 DOC/unRarLicense.txt "$pkgdir/usr/share/licenses/$name/unRarLicense.txt"
'''
