[package]
name     = "kguiaddons"
version  = "6.27.0"
release  = 1
summary  = "KDE: utilities for graphical applications"
homepage = "https://community.kde.org/Frameworks"
license  = ["LGPL-2.1-or-later"]
arch     = ["x86_64"]

depends     = ["qt6-base", "qt6-wayland", "wayland"]
makedepends = ["plasma-wayland-protocols", "qt6-tools", "qt6-declarative", "extra-cmake-modules", "cmake", "ninja", "python", "qt6-base", "qt6-wayland", "wayland-protocols"]
options     = ["!lto"]

[[source]]
url    = "https://download.kde.org/stable/frameworks/6.27/kguiaddons-6.27.0.tar.xz"
sha256 = "29b043480c45d3e51c57cac74fd83589cc7729c907a6585b72880cbf07feaf82"

[steps]
build = '''
cmake -S "kguiaddons-$version" -B build -G Ninja -D CMAKE_BUILD_TYPE=Release -D CMAKE_INSTALL_PREFIX=/usr -D KDE_INSTALL_LIBDIR=lib -D KDE_INSTALL_USE_QT_SYS_PATHS=ON -D BUILD_TESTING=OFF -D BUILD_QCH=OFF -D BUILD_PYTHON_BINDINGS=OFF;
cmake --build build
'''
package = '''
DESTDIR="$pkgdir" cmake --install build
'''
