[package]
name     = "polkit"
version  = "127"
release  = 1
summary  = "Application development toolkit for controlling system-wide privileges"
homepage = "https://github.com/polkit-org/polkit"
license  = ["LGPL-2.0-or-later"]
arch     = ["x86_64"]

depends     = ["glib2", "expat", "pam", "duktape", "systemd"]
makedepends = ["meson", "ninja", "gettext", "glib2-devel", "duktape"]
provides    = ["libpolkit-gobject-1.so", "libpolkit-agent-1.so"]

[[source]]
url    = "https://github.com/polkit-org/polkit/archive/127/polkit-127.tar.gz"
sha256 = "9b7bc16f086479dcc626c575976568ba4a85d34297a750d8ab3d2e57f6d8b988"

[steps]
build = '''
arch-meson "$name-$version" build -D authfw=pam -D introspection=false -D man=false -D gtk_doc=false -D tests=false -D examples=false -D session_tracking=logind -D systemdsystemunitdir=/usr/lib/systemd/system;
meson compile -C build
'''
package = '''
meson install -C build --destdir "$pkgdir";
install -Dm644 "$name-$version/COPYING" "$pkgdir/usr/share/licenses/$name/COPYING"
'''
