[package]
name     = "networkmanager"
version  = "1.50.0"
release  = 1
summary  = "Network connection manager (NetworkManager daemon + libnm)"
homepage = "https://networkmanager.dev/"
license  = ["GPL-2.0-or-later", "LGPL-2.1-or-later"]
arch     = ["x86_64"]

depends     = ["glibc", "glib2", "libnl", "nss", "libndp", "jansson", "curl", "libpsl", "polkit", "util-linux", "readline", "dbus", "libmnl"]
makedepends = ["meson", "ninja", "pkgconf", "glib2", "glib2-devel", "libnl", "nss", "libndp", "jansson", "curl", "libpsl", "polkit", "util-linux", "dbus", "libmnl", "python", "python-gobject", "libxslt", "docbook-xsl"]
provides    = ["libnm.so", "libnmova"]

[[source]]
url    = "https://download.gnome.org/sources/NetworkManager/1.50/NetworkManager-1.50.0.tar.xz"
sha256 = "fc03e7388a656cebc454c5d89481626122b1975d7c26babc64dc7e488faa66e3"

[steps]
build = '''
arch-meson "NetworkManager-$version" build \
  -D crypto=nss -D wifi=true -D iwd=false \
  -D modem_manager=false -D ppp=false -D ovs=false -D teamdctl=false \
  -D bluez5_dun=false -D nmtui=false -D nmcli=true \
  -D introspection=false -D vapi=false -D docs=false -D tests=no \
  -D selinux=false -D libaudit=no -D libpsl=true \
  -D session_tracking=systemd -D suspend_resume=systemd \
  -D config_plugins_default=keyfile -D config_dhcp_default=internal -D qt=false
meson compile -C build
'''
package = '''
meson install -C build --destdir "$pkgdir"
'''
