[package]
name     = "mtdev"
version  = "1.1.7"
release  = 1
summary  = "Multitouch protocol translation library (KWin/libinput)"
homepage = "https://bitmath.org/code/mtdev/"
license  = ["MIT"]
arch     = ["x86_64"]

depends     = ["glibc"]
options     = ["!lto"]

[[source]]
url    = "https://bitmath.org/code/mtdev/mtdev-1.1.7.tar.bz2"
sha256 = "a107adad2101fecac54ac7f9f0e0a0dd155d954193da55c2340c97f2ff1d814e"

[steps]
build = '''
cd "mtdev-$version";
./configure --prefix=/usr --libdir=/usr/lib --disable-static;
make
'''
package = '''
cd "mtdev-$version";
make DESTDIR="$pkgdir" install
'''
