[package]
name = "libtirpc"
version = "1.3.6"
release = 1
summary = "Transport Independent RPC library (SunRPC replacement)"
homepage = "https://sourceforge.net/projects/libtirpc/"
license = ["BSD-3-Clause"]
arch = ["x86_64"]
depends = ["glibc", "krb5"]
makedepends = ["pkgconf"]
provides = ["libtirpc.so"]
[[source]]
url = "libtirpc-1.3.6.tar.bz2::https://downloads.sourceforge.net/libtirpc/libtirpc-1.3.6.tar.bz2"
sha256 = "SKIP"
[steps]
build = '''
cd "libtirpc-$version";
./configure --prefix=/usr --sysconfdir=/etc --disable-static --disable-gssapi;
make
'''
package = '''
cd "libtirpc-$version";
make DESTDIR="$pkgdir" install
'''
