[package]
name     = "kjobwidgets"
version  = "6.27.0"
release  = 1
summary  = "KDE: widgets for tracking KJob progress"
homepage = "https://community.kde.org/Frameworks"
license  = ["LGPL-2.1-or-later"]
arch     = ["x86_64"]

depends     = ["qt6-base", "kcoreaddons", "kwidgetsaddons", "kwindowsystem"]
makedepends = ["qt6-tools", "qt6-declarative", "extra-cmake-modules", "cmake", "ninja", "python", "qt6-base"]
options     = ["!lto"]

[[source]]
url    = "https://download.kde.org/stable/frameworks/6.27/kjobwidgets-6.27.0.tar.xz"
sha256 = "3149cd07d82204c6bfa8d86c590bf0c92905e1b5b075c7b543540916a61d7a03"

[steps]
build = '''
cmake -S "kjobwidgets-$version" -B build -G Ninja -D CMAKE_BUILD_TYPE=Release -D CMAKE_INSTALL_PREFIX=/usr -D KDE_INSTALL_LIBDIR=lib -D KDE_INSTALL_USE_QT_SYS_PATHS=ON -D BUILD_TESTING=OFF -D BUILD_QCH=OFF -D BUILD_PYTHON_BINDINGS=OFF;
cmake --build build
'''
package = '''
DESTDIR="$pkgdir" cmake --install build
'''
