[package]
name     = "kparts"
version  = "6.27.0"
release  = 1
summary  = "KDE: document-centric component framework"
homepage = "https://community.kde.org/Frameworks"
license  = ["LGPL-2.1-or-later"]
arch     = ["x86_64"]

depends     = ["qt6-base", "kconfig", "kcoreaddons", "ki18n", "kio", "kjobwidgets", "kservice", "ktextwidgets", "kwidgetsaddons", "kxmlgui"]
makedepends = ["qt6-tools", "qt6-declarative", "extra-cmake-modules", "cmake", "ninja", "python", "qt6-base"]
options     = ["!lto"]

[[source]]
url    = "https://download.kde.org/stable/frameworks/6.27/kparts-6.27.0.tar.xz"
sha256 = "0c2ce39f110e12ff0882c725bee7455b9085489c12d31eb4b3164b150fb8de24"

[steps]
build = '''
cmake -S "kparts-$version" -B build -G Ninja -D CMAKE_BUILD_TYPE=Release -D CMAKE_INSTALL_PREFIX=/usr -D KDE_INSTALL_LIBDIR=lib -D KDE_INSTALL_USE_QT_SYS_PATHS=ON -D BUILD_TESTING=OFF -D BUILD_QCH=OFF -D BUILD_PYTHON_BINDINGS=OFF;
cmake --build build
'''
package = '''
DESTDIR="$pkgdir" cmake --install build
'''
