[package]
name     = "kglobalaccel"
version  = "6.27.0"
release  = 1
summary  = "KDE: global keyboard shortcuts"
homepage = "https://community.kde.org/Frameworks"
license  = ["LGPL-2.1-or-later"]
arch     = ["x86_64"]

depends     = ["qt6-base", "qt6-declarative", "kconfig", "kcoreaddons", "kcrash", "kdbusaddons", "kwindowsystem", "libx11", "libxcb"]
makedepends = ["qt6-tools", "qt6-declarative", "extra-cmake-modules", "cmake", "ninja", "python", "qt6-base", "qt6-declarative"]
options     = ["!lto"]

[[source]]
url    = "https://download.kde.org/stable/frameworks/6.27/kglobalaccel-6.27.0.tar.xz"
sha256 = "e7ba1601a159ea79f424a4d53647415393f90dbeda1e3216d023eeb5420837d3"

[steps]
build = '''
cmake -S "kglobalaccel-$version" -B build -G Ninja -D CMAKE_BUILD_TYPE=Release -D CMAKE_INSTALL_PREFIX=/usr -D KDE_INSTALL_LIBDIR=lib -D KDE_INSTALL_USE_QT_SYS_PATHS=ON -D BUILD_TESTING=OFF -D BUILD_QCH=OFF -D BUILD_PYTHON_BINDINGS=OFF;
cmake --build build
'''
package = '''
DESTDIR="$pkgdir" cmake --install build
'''
