[package]
name     = "gdbm"
version  = "1.24"
release  = 1
summary  = "GNU database library (dbm) with the ndbm/dbm compatibility shim"
homepage = "https://www.gnu.org/software/gdbm/"
license  = ["GPL-3.0-or-later"]
arch     = ["x86_64"]

depends     = ["glibc", "readline"]

[[source]]
url    = "https://ftp.gnu.org/gnu/gdbm/gdbm-1.24.tar.gz"
sha256 = "695e9827fdf763513f133910bc7e6cfdb9187943a4fec943e57449723d2b8dbf"

[steps]
build = '''
cd "$name-$version";
./configure --prefix=/usr --disable-static --enable-libgdbm-compat CFLAGS="${CFLAGS:-} -std=gnu17";
make
'''
package = '''
cd "$name-$version";
make DESTDIR="$pkgdir" install;
install -Dm644 COPYING "$pkgdir/usr/share/licenses/$name/COPYING"
'''
