[package]
name     = "gperf"
version  = "3.1"
release  = 1
summary  = "Perfect hash function generator"
homepage = "https://www.gnu.org/software/gperf/"
license  = ["GPL-3.0-or-later"]
arch     = ["x86_64"]

depends     = ["glibc", "gcc-libs"]
makedepends = ["make", "gcc"]

[[source]]
url    = "https://ftp.gnu.org/gnu/gperf/gperf-3.1.tar.gz"
sha256 = "588546b945bba4b70b6a3a616e80b4ab466e3f33024a352fc2198112cdbb3ae2"

[steps]
build = '''
cd "$name-$version";
./configure --prefix=/usr;
make
'''
package = '''
cd "$name-$version";
make DESTDIR="$pkgdir" install
'''
