[package]
name     = "gperf"
version  = "3.3"
release  = 1
summary  = "Perfect hash function generator"
homepage = "https://www.gnu.org/software/gperf/"
license  = ["GPL-3.0-or-later"]
arch     = ["x86_64"]

depends     = ["glibc", "gcc-libs"]
makedepends = ["make", "gcc"]

[[source]]
url    = "https://ftp.gnu.org/gnu/gperf/gperf-3.3.tar.gz"
sha256 = "fd87e0aba7e43ae054837afd6cd4db03a3f2693deb3619085e6ed9d8d9604ad8"

[steps]
build = '''
cd "$name-$version";
./configure --prefix=/usr;
make
'''
package = '''
cd "$name-$version";
make DESTDIR="$pkgdir" install
'''
