[package]
name     = "kpipewire"
version  = "6.7.0"
release  = 1
summary  = "KDE: PipeWire integration for screen capture"
homepage = "https://kde.org/plasma-desktop/"
license  = ["GPL-2.0-or-later"]
arch     = ["x86_64"]

depends     = ["ffmpeg", "kcoreaddons", "ki18n", "libdrm", "libepoxy", "libpipewire", "libva", "mesa", "qt6-base", "qt6-declarative"]
makedepends = ["kdoctools", "extra-cmake-modules", "cmake", "ninja", "python", "qt6-base", "qt6-declarative", "qt6-tools", "pipewire", "wayland-protocols", "plasma-wayland-protocols"]
options     = ["!lto"]

[[source]]
url    = "https://download.kde.org/stable/plasma/6.7.0/kpipewire-6.7.0.tar.xz"
sha256 = "dbf839b779c508c2020bdf9d642762387cba85059291deab38e8a0c15223badb"

[steps]
build = '''
cmake -S "kpipewire-$version" -B build -G Ninja -D CMAKE_BUILD_TYPE=Release -D CMAKE_INSTALL_PREFIX=/usr -D KDE_INSTALL_LIBDIR=lib -D KDE_INSTALL_LIBEXECDIR=lib -D KDE_INSTALL_USE_QT_SYS_PATHS=ON -D BUILD_TESTING=OFF -D BUILD_QCH=OFF -D BUILD_PYTHON_BINDINGS=OFF;
cmake --build build
'''
package = '''
DESTDIR="$pkgdir" cmake --install build
'''
