[package]
name     = "lzo"
version  = "2.10"
release  = 1
summary  = "Portable lossless data compression library"
homepage = "https://www.freedesktop.org/"
license  = ["LGPL-2.1-or-later"]
arch     = ["x86_64"]

depends     = ["glibc"]
options     = ["!lto"]

[[source]]
url    = "lzo-2.10.tar.gz::https://www.oberhumer.com/opensource/lzo/download/lzo-2.10.tar.gz"
sha256 = "c0f892943208266f9b6543b3ae308fab6284c5c90e627931446fb49b4221a072"

[steps]
build = '''
cd "lzo-2.10";
./configure --prefix=/usr --sysconfdir=/etc --localstatedir=/var --enable-shared;
make
'''
package = '''
cd "lzo-2.10";
make DESTDIR="$pkgdir" install
'''
