[package]
name     = "libxkbcommon"
version  = "1.7.0"
release  = 2
summary  = "Keyboard handling library using XKB data (Wayland + X11)"
homepage = "https://xkbcommon.org/"
license  = ["MIT"]
arch     = ["x86_64"]

depends     = ["xkeyboard-config", "libxml2", "libxcb", "glibc"]
makedepends = ["meson", "ninja", "bison", "wayland", "wayland-protocols", "libxcb"]
provides    = ["libxkbcommon.so", "libxkbcommon-x11.so", "libxkbregistry.so"]

[[source]]
url    = "https://xkbcommon.org/download/libxkbcommon-1.7.0.tar.xz"
sha256 = "65782f0a10a4b455af9c6baab7040e2f537520caa2ec2092805cdfd36863b247"

[steps]
build = '''
arch-meson "$name-$version" build -D enable-docs=false -D enable-x11=true -D enable-wayland=true -D xkb-config-root=/usr/share/X11/xkb;
meson compile -C build
'''
package = '''
meson install -C build --destdir "$pkgdir";
install -Dm644 "$name-$version/LICENSE" "$pkgdir/usr/share/licenses/$name/LICENSE"
'''
