[package]
name     = "libffi"
version  = "3.7.1"
release  = 1
summary  = "Portable foreign-function interface library (libffi)"
homepage = "https://sourceware.org/libffi/"
license  = ["MIT"]
arch     = ["x86_64"]

depends     = ["glibc"]
provides    = ["libffi.so"]

[[source]]
url    = "https://github.com/libffi/libffi/releases/download/v3.7.1/libffi-3.7.1.tar.gz"
sha256 = "d5e9a6638ddbd2513ddb54518eb67e4bbe6fa707bcc01c10f6212f0a088d819d"

[steps]
build = '''
cd "$name-$version";
./configure --prefix=/usr --disable-static --disable-exec-static-tramp;
make
'''
package = '''
cd "$name-$version";
make DESTDIR="$pkgdir" install
'''
