[package]
name     = "libffi"
version  = "3.8.0"
release  = 1
summary  = "Portable foreign-function interface library (libffi)"
homepage = "https://sourceware.org/libffi/"
license  = ["MIT"]
arch     = ["x86_64"]

depends     = ["glibc"]
provides    = ["libffi.so"]

[[source]]
url    = "https://github.com/libffi/libffi/releases/download/v3.8.0/libffi-3.8.0.tar.gz"
sha256 = "7da3e2d9a171eb0a038f592ecad3ff2bb2550f3496d87b3b29ad0cf4430c0db4"

[steps]
build = '''
cd "$name-$version";
./configure --prefix=/usr --libdir=/usr/lib --disable-static --disable-exec-static-tramp;
make
'''
package = '''
cd "$name-$version";
make DESTDIR="$pkgdir" install
'''
