[package]
name     = "powerdevil"
version  = "6.7.0"
release  = 1
summary  = "KDE: power management daemon for Plasma"
homepage = "https://kde.org/plasma-desktop/"
license  = ["GPL-2.0-or-later"]
arch     = ["x86_64"]

depends     = ["ddcutil", "plasma-activities", "kauth", "kcmutils", "kconfig", "kcoreaddons", "kcrash", "kdbusaddons", "kglobalaccel", "ki18n", "kidletime", "kirigami", "kitemmodels", "knotifications", "kpackage", "kservice", "kxmlgui", "libkscreen", "libplasma", "libxcb", "plasma-workspace", "qt6-base", "qt6-declarative", "solid", "wayland", "qcoro"]
makedepends = ["plasma-wayland-protocols", "qcoro", "kdoctools", "extra-cmake-modules", "cmake", "ninja", "python", "qt6-base", "qt6-declarative", "qt6-tools"]
options     = ["!lto"]

[[source]]
url    = "https://download.kde.org/stable/plasma/6.7.0/powerdevil-6.7.0.tar.xz"
sha256 = "7635efffd503e78d92bcc03033d5681e51577ec92bc6da72f2ab2828bb0a34db"

[steps]
build = '''
cmake -S "powerdevil-$version" -B build -G Ninja -D CMAKE_BUILD_TYPE=Release -D CMAKE_INSTALL_PREFIX=/usr -D KDE_INSTALL_LIBDIR=lib -D KDE_INSTALL_LIBEXECDIR=lib -D KDE_INSTALL_USE_QT_SYS_PATHS=ON -D BUILD_TESTING=OFF -D BUILD_QCH=OFF -D BUILD_PYTHON_BINDINGS=OFF;
cmake --build build
'''
package = '''
DESTDIR="$pkgdir" cmake --install build
'''
