[package]
name="libdeflate"
version="1.20"
release=1
summary="Fast DEFLATE/zlib/gzip compression and decompression (libdeflate)"
homepage="https://github.com/ebiggers/libdeflate"
license=["MIT"]
arch=["x86_64"]
depends=["glibc"]
makedepends=["cmake","ninja"]
provides=["libdeflate.so"]
[[source]]
url="https://github.com/ebiggers/libdeflate/archive/v1.20/libdeflate-1.20.tar.gz"
sha256="ed1454166ced78913ff3809870a4005b7170a6fd30767dc478a09b96847b9c2a"
[steps]
build='''
cmake -B build -S "$name-$version" -G Ninja -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release -DLIBDEFLATE_BUILD_STATIC_LIB=OFF
cmake --build build
'''
package='''
DESTDIR="$pkgdir" cmake --install build
'''
