[package]
name     = "libdisplay-info"
version  = "0.3.0"
release  = 1
summary  = "EDID/DisplayID parsing (KWin)"
homepage = "https://blueberry.linux/"
license  = ["custom"]
arch     = ["x86_64"]

depends     = ["glibc"]
makedepends = ["meson", "ninja", "hwdata", "python"]
options     = ["!lto"]

[[source]]
url    = "https://gitlab.freedesktop.org/emersion/libdisplay-info/-/releases/0.3.0/downloads/libdisplay-info-0.3.0.tar.xz"
sha256 = "6ae77cd937f9cf7d1321d35c116062c4911e8447010a6a713ac4286f7a9d5987"

[steps]
build = '''
function arch-meson () 
{ 
    meson setup "$@"
};
meson setup "libdisplay-info-0.3.0" build --prefix=/usr --buildtype=release -Dwerror=false;
meson compile -C build
'''
package = '''
meson install -C build --destdir "$pkgdir"
'''
