[package]
name     = "qt6-multimedia"
version  = "6.11.1"
release  = 1
summary  = "Qt 6 multimedia (audio/video/camera) module"
homepage = "https://www.qt.io/"
license  = ["LGPL-3.0-only"]
arch     = ["x86_64"]

depends     = ["qt6-base", "qt6-declarative", "qt6-shadertools", "ffmpeg", "libpulse", "libva", "pipewire", "libxrandr", "libxext", "libxfixes", "libxcb"]
makedepends = ["vulkan-headers", "libxrandr", "libxext", "libxfixes", "libxcb", "cmake", "ninja", "python", "qt6-base", "qt6-declarative", "perl", "qt6-shadertools", "ffmpeg", "pipewire"]
options     = ["!lto"]

[[source]]
url    = "https://download.qt.io/official_releases/qt/6.11/6.11.1/submodules/qtmultimedia-everywhere-src-6.11.1.tar.xz"
sha256 = "390f8e52ddee3aca5c4de7eead900c84c4fa61ff6d1f0ebea9c7543365c09b0a"

[steps]
build = '''
cmake -S "qtmultimedia-everywhere-src-$version" -B build -G Ninja -D CMAKE_BUILD_TYPE=Release -D CMAKE_INSTALL_PREFIX=/usr -D INSTALL_LIBDIR=/usr/lib -D INSTALL_ARCHDATADIR=/usr/lib/qt6 -D QT_BUILD_EXAMPLES=OFF -D QT_BUILD_TESTS=OFF;
cmake --build build
'''
package = '''
DESTDIR="$pkgdir" cmake --install build
'''
