[package]
name     = "milou"
version  = "6.7.0"
release  = 1
summary  = "KDE: unified search interface for Plasma"
homepage = "https://kde.org/plasma-desktop/"
license  = ["GPL-2.0-or-later"]
arch     = ["x86_64"]

depends     = ["kconfig", "kcoreaddons", "kirigami", "krunner", "ksvg", "libplasma", "qt6-base", "qt6-declarative"]
makedepends = ["kdoctools", "extra-cmake-modules", "cmake", "ninja", "python", "qt6-base", "qt6-declarative", "qt6-tools"]
options     = ["!lto"]

[[source]]
url    = "https://download.kde.org/stable/plasma/6.7.0/milou-6.7.0.tar.xz"
sha256 = "8c94a4c3cef9bc625b541cb3d4c2f0a95bfa13d31f3c180633f7ef9d2701db1e"

[steps]
build = '''
cmake -S "milou-$version" -B build -G Ninja -D CMAKE_BUILD_TYPE=Release -D CMAKE_INSTALL_PREFIX=/usr -D KDE_INSTALL_LIBDIR=lib -D KDE_INSTALL_LIBEXECDIR=lib -D KDE_INSTALL_USE_QT_SYS_PATHS=ON -D BUILD_TESTING=OFF -D BUILD_QCH=OFF -D BUILD_PYTHON_BINDINGS=OFF;
cmake --build build
'''
package = '''
DESTDIR="$pkgdir" cmake --install build
'''
