[package]
name     = "xcb-util-image"
version  = "0.4.1"
release  = 1
summary  = "XCB utility library: xcb-util-image"
homepage = "https://xcb.freedesktop.org/"
license  = ["MIT"]
arch     = ["x86_64"]

depends     = ["libxcb", "xcb-util"]
makedepends = ["xcb-proto", "xorgproto", "xorg-util-macros", "libxcb", "pkgconf", "gperf"]
provides    = ["libxcb-image.so"]

[[source]]
url    = "https://xorg.freedesktop.org/archive/individual/lib/xcb-util-image-0.4.1.tar.xz"
sha256 = "ccad8ee5dadb1271fd4727ad14d9bd77a64e505608766c4e98267d9aede40d3d"

[steps]
build = '''
cd "$name-$version";
./configure --prefix=/usr --disable-static;
make
'''
package = '''
cd "$name-$version";
make DESTDIR="$pkgdir" install;
install -Dm644 COPYING "$pkgdir/usr/share/licenses/$name/COPYING"
'''
