[package]
name     = "qt6-shadertools"
version  = "6.11.1"
release  = 1
summary  = "Qt 6 tools and APIs for working with shaders (required by Qt Quick)"
homepage = "https://www.qt.io/"
license  = ["LGPL-3.0-only"]
arch     = ["x86_64"]

depends     = ["qt6-base"]
makedepends = ["cmake", "ninja", "python", "qt6-base", "perl"]
options     = ["!lto"]

[[source]]
url    = "https://download.qt.io/official_releases/qt/6.11/6.11.1/submodules/qtshadertools-everywhere-src-6.11.1.tar.xz"
sha256 = "2075052f9b23bcf9de045bbd180037084942f82cce870aab14a1454902c982fc"

[steps]
build = '''
export CXXFLAGS="${CXXFLAGS} -include cstdint";
cmake -S "qtshadertools-everywhere-src-$version" -B build -G Ninja -D CMAKE_BUILD_TYPE=Release -D CMAKE_INSTALL_PREFIX=/usr -D INSTALL_LIBDIR=/usr/lib -D INSTALL_ARCHDATADIR=/usr/lib/qt6 -D QT_BUILD_EXAMPLES=OFF -D QT_BUILD_TESTS=OFF;
cmake --build build
'''
package = '''
DESTDIR="$pkgdir" cmake --install build;
install -Dm644 "qtshadertools-everywhere-src-$version/LICENSES/LGPL-3.0-only.txt" "$pkgdir/usr/share/licenses/$name/LICENSE" 2> /dev/null || true
'''
