[package]
name     = "patch"
version  = "2.7.6"
release  = 2
summary  = "Apply a diff file to an original"
homepage = "https://savannah.gnu.org/projects/patch/"
license  = ["GPL-3.0-or-later"]
arch     = ["x86_64"]

depends     = ["glibc", "attr"]

[[source]]
url    = "https://ftp.gnu.org/gnu/patch/patch-2.7.6.tar.xz"
sha256 = "ac610bda97abe0d9f6b7c963255a11dcb196c25e337c61f94e4778d632f1d8fd"

[steps]
build = '''
cd "$name-$version";
./configure --prefix=/usr;
make
'''
package = '''
cd "$name-$version";
make DESTDIR="$pkgdir" install;
install -Dm644 COPYING "$pkgdir/usr/share/licenses/$name/COPYING"
'''
