[package]
name     = "patch"
version  = "2.8"
release  = 1
summary  = "Apply a diff file to an original"
homepage = "https://savannah.gnu.org/projects/patch/"
license  = ["GPL-3.0-or-later"]
arch     = ["x86_64"]

depends     = ["glibc", "attr"]

[[source]]
url    = "https://ftp.gnu.org/gnu/patch/patch-2.8.tar.xz"
sha256 = "f87cee69eec2b4fcbf60a396b030ad6aa3415f192aa5f7ee84cad5e11f7f5ae3"

[steps]
build = '''
cd "$name-$version";
./configure --prefix=/usr;
make
'''
package = '''
cd "$name-$version";
make DESTDIR="$pkgdir" install;
install -Dm644 COPYING "$pkgdir/usr/share/licenses/$name/COPYING"
'''
