[package]
name     = "libxdamage"
version  = "1.1.7"
release  = 1
summary  = "X11 Damage extension library"
homepage = "https://www.freedesktop.org/"
license  = ["LGPL-2.1-or-later"]
arch     = ["x86_64"]

depends     = ["libx11", "libxfixes"]
makedepends = ["pkgconf", "xorgproto"]
options     = ["!lto"]

[[source]]
url    = "libXdamage-1.1.7.tar.xz::https://www.x.org/releases/individual/lib/libXdamage-1.1.7.tar.xz"
sha256 = "127067f521d3ee467b97bcb145aeba1078e2454d448e8748eb984d5b397bde24"

[steps]
build = '''
cd "libXdamage-1.1.7";
./configure --prefix=/usr --sysconfdir=/etc --localstatedir=/var;
make
'''
package = '''
cd "libXdamage-1.1.7";
make DESTDIR="$pkgdir" install
'''
