#!/bin/sh
# mkrepokey.sh — (re)generate src/bpm-rs/src/repokey.rs from an ed25519 keypair.
#
# Usage: tools/mkrepokey.sh [signing-key.pem]
#   Default key: ~/.config/bpm/repo-ed25519.pem (generated if absent).
#   Extracts the raw 32-byte ed25519 public key and writes it as a Rust byte
#   array into src/bpm-rs/src/repokey.rs. Rebuild bpm afterwards.
#
# The PRIVATE key never enters the repo; only the public key is baked in.
# tools/bpmrepo.sh signs bpm.index with the private key; bpm verifies (src/sig.rs).

set -eu
KEY="${1:-$HOME/.config/bpm/repo-ed25519.pem}"
HERE=$(unset CDPATH; cd -- "$(dirname -- "$0")" && pwd)
OUT="$HERE/../src/bpm-rs/src/repokey.rs"

command -v openssl >/dev/null 2>&1 || { echo "mkrepokey: need openssl" >&2; exit 1; }

if [ ! -f "$KEY" ]; then
    mkdir -p "$(dirname -- "$KEY")"
    openssl genpkey -algorithm ed25519 -out "$KEY"
    chmod 600 "$KEY"
    echo "mkrepokey: generated $KEY"
fi

# ed25519 SubjectPublicKeyInfo (DER) = 12-byte prefix + the 32-byte raw key.
HEX=$(openssl pkey -in "$KEY" -pubout -outform DER 2>/dev/null | tail -c 32 | xxd -p -c 32)
[ "${#HEX}" -eq 64 ] || { echo "mkrepokey: expected 32-byte key, got $(( ${#HEX} / 2 ))" >&2; exit 1; }

{
    echo "//! repokey.rs — baked-in repository signing public key (ed25519)."
    echo "//!"
    echo "//! Auto-generated by tools/mkrepokey.sh from the maintainer keypair. The"
    echo "//! matching PRIVATE key lives outside this repo and signs bpm.index"
    echo "//! (tools/bpmrepo.sh). bpm verifies signatures against this key (src/sig.rs)."
    echo "//! Rotate: rerun tools/mkrepokey.sh and rebuild bpm."
    echo ""
    echo "pub(crate) const REPO_PUBKEY: [u8; 32] = ["
    printf '%s\n' "$HEX" | awk '{
        line = "    ";
        for (i = 1; i <= length($0); i += 2) {
            line = line sprintf("0x%s, ", substr($0, i, 2));
            if ((i + 1) % 32 == 0) { print line; line = "    "; }
        }
        if (line != "    ") print line;
    }'
    echo "];"
} > "$OUT"

echo "mkrepokey: wrote $OUT"
