[package]
name     = "kunitconversion"
version  = "6.27.0"
release  = 1
summary  = "KDE: unit conversion library"
homepage = "https://community.kde.org/Frameworks"
license  = ["LGPL-2.1-or-later"]
arch     = ["x86_64"]

depends     = ["qt6-base", "qt6-declarative"]
makedepends = ["qt6-tools", "qt6-declarative", "extra-cmake-modules", "cmake", "ninja", "python", "qt6-base", "qt6-declarative"]
options     = ["!lto"]

[[source]]
url    = "https://download.kde.org/stable/frameworks/6.27/kunitconversion-6.27.0.tar.xz"
sha256 = "404e064114c95eca0ef759b96ca4e0ba5f9b8bc563138574358270963f3f5554"

[steps]
build = '''
cmake -S "kunitconversion-$version" -B build -G Ninja -D CMAKE_BUILD_TYPE=Release -D CMAKE_INSTALL_PREFIX=/usr -D KDE_INSTALL_LIBDIR=lib -D KDE_INSTALL_USE_QT_SYS_PATHS=ON -D BUILD_TESTING=OFF -D BUILD_QCH=OFF -D BUILD_PYTHON_BINDINGS=OFF;
cmake --build build
'''
package = '''
DESTDIR="$pkgdir" cmake --install build
'''
