[package]
name     = "brotli"
version  = "1.2.0"
release  = 2
summary  = "Generic-purpose lossless compression algorithm library"
homepage = "https://github.com/google/brotli"
license  = ["MIT"]
arch     = ["x86_64"]

depends     = ["glibc"]
makedepends = ["cmake"]
provides    = ["libbrotlicommon.so", "libbrotlidec.so", "libbrotlienc.so"]

[[source]]
url    = "brotli-1.2.0.tar.gz::https://github.com/google/brotli/archive/refs/tags/v1.2.0.tar.gz"
sha256 = "816c96e8e8f193b40151dad7e8ff37b1221d019dbcb9c35cd3fadbfe6477dfec"

[steps]
build = '''
cd "$name-$version";
cmake -B build -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_INSTALL_LIBDIR=lib -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON;
cmake --build build
'''
package = '''
cd "$name-$version";
DESTDIR="$pkgdir" cmake --install build
'''
