[package]
name     = "screen"
version  = "5.0.2"
release  = 1
summary  = "Full-screen window manager that multiplexes a physical terminal"
homepage = "https://www.gnu.org/software/screen/"
license  = ["GPL-3.0-or-later"]
arch     = ["x86_64"]

depends     = ["glibc", "ncurses", "libxcrypt"]

[[source]]
url    = "https://ftp.gnu.org/gnu/screen/screen-5.0.2.tar.gz"
sha256 = "ca9a2c7e240919bc7ac12124593ae4529bb4eb5f7349d8857829b7e3f0b3b332"

[steps]
build = '''
cd "$name-$version";
./configure --prefix=/usr --enable-colors256 --enable-rxvt_osc --enable-telnet --disable-pam;
make
'''
package = '''
cd "$name-$version";
make DESTDIR="$pkgdir" install
'''
