[package]
name     = "mtr"
version  = "0.96"
release  = 1
summary  = "Combines the functionality of traceroute and ping into a single network diagnostic tool"
homepage = "https://www.bitwizard.nl/mtr/"
license  = ["GPL-2.0-only"]
arch     = ["x86_64"]

depends     = ["glibc", "ncurses", "libcap"]
makedepends = ["autoconf", "automake", "libtool", "pkgconf"]

[[source]]
url    = "https://github.com/traviscross/mtr/archive/v0.96/mtr-0.96.tar.gz"
sha256 = "73e6aef3fb6c8b482acb5b5e2b8fa7794045c4f2420276f035ce76c5beae632d"

[steps]
build = '''
cd "$name-$version";
./bootstrap.sh;
./configure --prefix=/usr --sysconfdir=/etc --mandir=/usr/share/man --without-gtk;
make
'''
package = '''
cd "$name-$version";
make DESTDIR="$pkgdir" install;
install -Dm644 COPYING "$pkgdir/usr/share/licenses/$name/COPYING"
'''
