[package]
name     = "mtr"
version  = "0.95"
release  = 1
summary  = "Combines the functionality of traceroute and ping into a single network diagnostic tool"
homepage = "https://www.bitwizard.nl/mtr/"
license  = ["GPL-2.0-only"]
arch     = ["x86_64"]

depends     = ["glibc", "ncurses", "libcap"]
makedepends = ["autoconf", "automake", "libtool", "pkgconf"]

[[source]]
url    = "https://github.com/traviscross/mtr/archive/v0.95/mtr-0.95.tar.gz"
sha256 = "12490fb660ba5fb34df8c06a0f62b4f9cbd11a584fc3f6eceda0a99124e8596f"

[steps]
build = '''
cd "$name-$version";
./bootstrap.sh;
./configure --prefix=/usr --sysconfdir=/etc --mandir=/usr/share/man --without-gtk;
make
'''
package = '''
cd "$name-$version";
make DESTDIR="$pkgdir" install;
install -Dm644 COPYING "$pkgdir/usr/share/licenses/$name/COPYING"
'''
