[package]
name     = "flex"
version  = "2.6.4"
release  = 1
summary  = "Fast lexical analyzer generator (lex-compatible)"
homepage = "https://github.com/westes/flex"
license  = ["BSD-2-Clause"]
arch     = ["x86_64"]

depends     = ["glibc", "m4"]
provides    = ["libfl.so"]
makedepends = ["m4", "bison", "make", "gcc"]

[[source]]
url    = "https://github.com/westes/flex/releases/download/v2.6.4/flex-2.6.4.tar.gz"
sha256 = "e87aae032bf07c26f85ac0ed3250998c37621d95f8bd748b31f15b33c45ee995"

[steps]
build = '''
cd "$name-$version";
export CFLAGS="${CFLAGS:-} -std=gnu17";
./configure --prefix=/usr --disable-static;
make
'''
package = '''
cd "$name-$version";
make DESTDIR="$pkgdir" install;
ln -sf flex "$pkgdir/usr/bin/lex"
'''
