[package]
name     = "bash"
version  = "5.3"
release  = 1
summary  = "The GNU Bourne Again shell"
homepage = "https://www.gnu.org/software/bash/bash.html"
license  = ["GPL-3.0-or-later"]
arch     = ["x86_64"]

depends     = ["glibc", "ncurses"]
provides    = ["sh"]

[[source]]
url    = "https://mirrors.kernel.org/gnu/bash/bash-5.3.tar.gz"
sha256 = "0d5cd86965f869a26cf64f4b71be7b96f90a3ba8b3d74e27e8e9d9d5550f31ba"

[steps]
build = '''
cd "$name-$version";
export CFLAGS="${CFLAGS:-} -std=gnu17";
./configure --prefix=/usr --without-bash-malloc --with-curses --enable-readline --with-installed-readline=no;
make
'''
package = '''
cd "$name-$version";
make DESTDIR="$pkgdir" install;
mkdir -p "$pkgdir/bin";
ln -sf ../usr/bin/bash "$pkgdir/bin/bash";
ln -sf bash "$pkgdir/usr/bin/sh";
ln -sf ../usr/bin/bash "$pkgdir/bin/sh"
'''
