[package]
name     = "bash"
version  = "5.2.37"
release  = 1
summary  = "The GNU Bourne Again shell"
homepage = "https://www.gnu.org/software/bash/bash.html"
license  = ["GPL-3.0-or-later"]
arch     = ["x86_64"]

depends     = ["glibc", "ncurses"]
provides    = ["sh"]

[[source]]
url    = "https://mirrors.kernel.org/gnu/bash/bash-5.2.37.tar.gz"
sha256 = "9599b22ecd1d5787ad7d3b7bf0c59f312b3396d1e281175dd1f8a4014da621ff"

[steps]
build = '''
cd "$name-$version";
export CFLAGS="${CFLAGS:-} -std=gnu17";
./configure --prefix=/usr --without-bash-malloc --with-curses --enable-readline --with-installed-readline=no;
make
'''
package = '''
cd "$name-$version";
make DESTDIR="$pkgdir" install;
mkdir -p "$pkgdir/bin";
ln -sf ../usr/bin/bash "$pkgdir/bin/bash";
ln -sf bash "$pkgdir/usr/bin/sh";
ln -sf ../usr/bin/bash "$pkgdir/bin/sh"
'''
